
function require_ex( _mname )
    package.loaded[_mname] = nil
    return require( _mname )    
end

------------------------------------------------------------------------------------------
--                              初始化LuaJIT
------------------------------------------------------------------------------------------
if g_debug then
    package.path = "./?.lua;./?.lc"
else
    --package.path = "./?.lc"
    package.path = "./?.lc"
end

require_ex( "jit/opt" ) 

if g_debug then
    if jit then
        jit.debug(2)
        jit.opt.start(3)
        c_log( "++++++++++++++++++LUAJIT(v1) DEBUG OPT LEVEL 3+++++++++++++++++++" )
    end
else
    if jit then
        jit.debug(0)
        jit.opt.start(3)
        c_log( "++++++++++++++++++LUAJIT(v1) RELEASE OPT LEVEL 3+++++++++++++++++++" )
    end
end

math.randomseed( os.time() )

------------------------------------------------------------------------------------------
--                              加载所有模块
------------------------------------------------------------------------------------------

GLOBAL_DATA_CONFIG = require_ex( "luacommon/setting/GLOBAL_DATA_CONFIG" )
BUFFS = require_ex( "luacommon/setting/BUFFS" ) 
ITEMS = require_ex( "luacommon/setting/ITEMS" )
MAILS = require_ex( "luacommon/setting/MAILS" )
EQUIPS = require_ex( "luacommon/setting/EQUIPS" )
EQUIP_NON_ATTR_BUFFS = require_ex("luacommon/setting/EQUIP_NON_ATTR_BUFFS")
EQUIP_ATTRS = require_ex( "luacommon/setting/EQUIP_ATTRS" )
RUNES = require_ex( "luacommon/setting/RUNES" )
SKILL_UNLOCK = require_ex( "luacommon/setting/SKILL_UNLOCK" )
TEAM_SKILL_UNLOCK = require_ex( "luacommon/setting/TEAM_SKILL_UNLOCK" )
SKILL_LEARN = require_ex( "luacommon/setting/SKILL_LEARN" )
TEAM_SKILL_LEARN = require_ex( "luacommon/setting/TEAM_SKILL_LEARN" )
TALENT_UNLOCK = require_ex("luacommon/setting/TALENT_UNLOCK")
ENERGY_CONFIG = require_ex( "luacommon/setting/ENERGY_CONFIG" )
NPC_SUITS = require_ex("luacommon/setting/NPC_SUITS")

PLAYER_ATTR = require_ex("luacommon/setting/PLAYER_ATTR")
require_ex( "luacommon/setting/JOBS" ) 
DAILY_GOALS = require_ex( "luacommon/setting/DAILY_GOALS" )
HONOR_HALL = require_ex( "luacommon/setting/HONOR_HALL")
GM_CMD_CFG = require_ex( "luacommon/setting/GM_CMD_CFG" )

GUILD_LEVEL_CONFIG = require_ex( "luacommon/setting/GUILD_LEVEL_CONFIG" )
GUILD_POPULARITY_CONFIG = require_ex( "luacommon/setting/GUILD_POPULARITY_CONFIG" )
GUILD_ROLE_PRIVILEGE_CONFIG = require_ex( "luacommon/setting/GUILD_ROLE_PRIVILEGE_CONFIG" )
GUILD_SYSTEM_CONFIG = require_ex( "luacommon/setting/GUILD_SYSTEM_CONFIG" )
ELAM_MILITARY_SUPPLIES_CFG = require_ex( "luacommon/setting/ELAM_MILITARY_SUPPLIES_CFG" )
ACTIVITY_INSTANCE_CONFIG = require_ex("luacommon/setting/ACTIVITY_INSTANCE_CONFIG")

GOD_DIVINATION_CONFIG = require_ex( "luacommon/setting/GOD_DIVINATION_CONFIG" )
GOD_DIVINATION_ASTROLABE_CONFIG = require_ex( "luacommon/setting/GOD_DIVINATION_ASTROLABE_CONFIG" )
GOD_DIVINATION_RUNE_CONFIG = require_ex( "luacommon/setting/GOD_DIVINATION_RUNE_CONFIG" )
RECHARGE_AWARD_CONFIG = require_ex(  "luacommon/setting/RECHARGE_AWARD_CONFIG" )
HOLIDAY_SIGNIN_AWARD_GLOBAL_CONFIG = require_ex( "luacommon/setting/HOLIDAY_SIGNIN_AWARD_GLOBAL_CONFIG" )
HOLIDAY_SIGNIN_AWARD_CONFIG = require_ex( "luacommon/setting/HOLIDAY_SIGNIN_AWARD_CONFIG" )
MONTHLY_SIGNIN_AWARD_GLOBAL_CONFIG = require_ex( "luacommon/setting/MONTHLY_SIGNIN_AWARD_GLOBAL_CONFIG" )
MONTHLY_SIGNIN_AWARD_CONFIG = require_ex( "luacommon/setting/MONTHLY_SIGNIN_AWARD_CONFIG" )
DAILY_ONLINE_AWARD_CONFIG = require_ex( "luacommon/setting/DAILY_ONLINE_AWARD_CONFIG" )
CYCLED_RECHARGE_AWARD_CONFIG = require_ex( "luacommon/setting/CYCLED_RECHARGE_AWARD_CONFIG" )
GROWTH_FUND_CONFIG = require_ex( "luacommon/setting/GROWTH_FUND_CONFIG" )
GROWTH_FUND_GLOBAL_CONFIG = require_ex( "luacommon/setting/GROWTH_FUND_GLOBAL_CONFIG" )
LOGIN_ACTIVITY_CONFIG = require_ex( "luacommon/setting/LOGIN_ACTIVITY_CONFIG" )
HALF_PRICE_CONFIG = require_ex( "luacommon/setting/HALF_PRICE_CONFIG" )
FIRST_RECHARGE_AWARD = require_ex( "luacommon/setting/FIRST_RECHARGE_AWARD" )
GUILD_ROLE_WELFARE_GLOBAL_CONFIG = require_ex( "luacommon/setting/GUILD_ROLE_WELFARE_GLOBAL_CONFIG" )
GUILD_ROLE_RANK_AWARD_CONFIG = require_ex( "luacommon/setting/GUILD_ROLE_RANK_AWARD_CONFIG" )
GUILD_ROLE_PROTECT_CITY_AWARD_CONFIG = require_ex( "luacommon/setting/GUILD_ROLE_PROTECT_CITY_AWARD_CONFIG" )
GUILD_ROLE_FIGHT_AWARD_CONFIG = require_ex( "luacommon/setting/GUILD_ROLE_FIGHT_AWARD_CONFIG" )
GUILD_ROLE_ITEM_LIB_CONFIG = require_ex( "luacommon/setting/GUILD_ROLE_ITEM_LIB_CONFIG" )
PARCHMENT_CONFIG = require_ex( "luacommon/setting/PARCHMENT_CONFIG" )
RECHARGE_BIG_AWARD_CONFIG = require_ex( "luacommon/setting/RECHARGE_BIG_AWARD_CONFIG" )
CHAT_CONFIG = require_ex( "luacommon/setting/CHAT_CONFIG" )
EVENT_TEAM_LADDER_CONFIG = require_ex( "luacommon/setting/EVENT_TEAM_LADDER_CONFIG" )

LEVEL_RECHARGE_ITEM_GIFT_GLOBAL_CONFIG = require_ex( "luacommon/setting/LEVEL_RECHARGE_ITEM_GIFT_GLOBAL_CONFIG" )
LEVEL_RECHARGE_ITEM_GIFT = require_ex( "luacommon/setting/LEVEL_RECHARGE_ITEM_GIFT" )
ONE_GOLD_LUCKY_DRAW_GOODS_CONFIG = require_ex( "luacommon/setting/ONE_GOLD_LUCKY_DRAW_GOODS_CONFIG" )
ONE_GOLD_LUCKY_DRAW_GLOBAL_CONFIG = require_ex( "luacommon/setting/ONE_GOLD_LUCKY_DRAW_GLOBAL_CONFIG" )
EGG_GLOBAL_CONFIG = require_ex( "luacommon/setting/EGG_GLOBAL_CONFIG" )
EGG_MON_CONFIG = require_ex( "luacommon/setting/EGG_MON_CONFIG" )
EGG_MON_REWARD_CONFIG = require_ex( "luacommon/setting/EGG_MON_REWARD_CONFIG" )
EGG_NPC_CONFIG = require_ex( "luacommon/setting/EGG_NPC_CONFIG" )
EGG_NPC_POS_CONFIG = require_ex( "luacommon/setting/EGG_NPC_POS_CONFIG" )
EGG_FEED_EVENT_CONFIG = require_ex( "luacommon/setting/EGG_FEED_EVENT_CONFIG" )
EGG_TYPE_CONFIG = require_ex( "luacommon/setting/EGG_TYPE_CONFIG" )
EGG_NUTRIENT_CONFIG = require_ex( "luacommon/setting/EGG_NUTRIENT_CONFIG" )
EGG_QUALITY_CONFIG = require_ex( "luacommon/setting/EGG_QUALITY_CONFIG" )

ONE_GOLD_LUCKY_DRAW_BONUS_GOODS_CONFIG = require_ex( "luacommon/setting/ONE_GOLD_LUCKY_DRAW_BONUS_GOODS_CONFIG" )
CHAT_GIFT_GLOBAL_CONFIG = require_ex( "luacommon/setting/CHAT_GIFT_GLOBAL_CONFIG" )
CHRISTMAS_SELL_GLOBAL_CONFIG = require_ex( "luacommon/setting/CHRISTMAS_SELL_GLOBAL_CONFIG" )
CHRISTMAS_RECHARGE_LUCKY_DRAW_GLOBAL_CONFIG = require_ex( "luacommon/setting/CHRISTMAS_RECHARGE_LUCKY_DRAW_GLOBAL_CONFIG" )
CHRISTMAS_SELL_ITEM_CONFIG = require_ex( "luacommon/setting/CHRISTMAS_SELL_ITEM_CONFIG" )
WING_UPGRADE_CONFIG = require_ex( "luacommon/setting/WING_UPGRADE_CONFIG" )
WING_CONFIG = require_ex( "luacommon/setting/WING_CONFIG" )

WING_CORE_UPGRADE_STAR = require_ex( "luacommon/setting/WING_CORE_UPGRADE_STAR") 
WING_SKILL_RANKS = require_ex( "luacommon/setting/WING_SKILL_RANKS")    
WING_SKILLS = require_ex( "luacommon/setting/WING_SKILLS")
WING_CORE_ATTRS = require_ex( "luacommon/setting/WING_CORE_ATTRS")
WING_CORES = require_ex( "luacommon/setting/WING_CORES")
--$SETTING_FILES

require_ex( "luacommon/limit" )
require_ex( "luacommon/share/share_const" )
require_ex( "luacommon/msg" )
require_ex( "luacommon/utils" )
require_ex( "luacommon/formula/fight_action" )
require_ex( "luacommon/object/obj_t" )
require_ex( "luacommon/object/ctrl_t" )
require_ex( "luacommon/object/drop_item_t")
require_ex( "luacommon/skill/skill_info" )
require_ex( "luacommon/object/spirit_t_module" )
require_ex( "luacommon/object/spirit_t_buff" )
require_ex( "luacommon/object/spirit_t_pasv" )
require_ex( "luacommon/object/spirit_t_fight" )
require_ex( "luacommon/object/spirit_t_color" )
require_ex( "luacommon/object/spirit_t" )
require_ex( "luacommon/object/player_t_module" )
require_ex( "luacommon/object/player_t_net" )
require_ex( "luacommon/object/player_t_fight" )
require_ex( "luacommon/object/player_t_copy" )
require_ex( "luacommon/object/player_t_skill" )
require_ex( "luacommon/object/player_t_element" )
require_ex( "luacommon/object/player_t_shop" )
require_ex( "luacommon/object/player_t_item" )
require_ex( "luacommon/object/player_t_rune" )
require_ex( "luacommon/object/player_t_quest")
require_ex( "luacommon/object/player_t_avatar" )
require_ex( "luacommon/object/player_t_soul" )
require_ex( "luacommon/object/player_t_mastery" )
require_ex( "luacommon/object/player_t_mail" )
require_ex( "luacommon/object/player_t_time" )
require_ex( "luacommon/object/player_t_param" )
require_ex( "luacommon/object/player_t_tower" )
require_ex( "luacommon/object/player_t_palace" )
require_ex( "luacommon/object/player_t_system_data" )
require_ex( "luacommon/object/player_t_attend" )
require_ex( "luacommon/object/player_t_daily_goals" )
require_ex( "luacommon/object/player_t_rmb" )
require_ex( "luacommon/object/player_t_snapshot" )
require_ex( "luacommon/object/player_t_guild" )
require_ex( "luacommon/object/player_t_friend" )
require_ex( "luacommon/object/player_t_team" )
require_ex( "luacommon/object/player_t_inst")
require_ex( "luacommon/object/player_t_guild_profession" )
require_ex( "luacommon/object/player_t_truncheon" )
require_ex( "luacommon/object/player_t_title" )
require_ex( "luacommon/object/player_t_equip_exchange_shop" )
require_ex( "luacommon/object/player_t_welfare" )
require_ex( "luacommon/object/player_t_trade" )
require_ex( "luacommon/object/player_t_vip" )
require_ex( "luacommon/object/player_t_auction" )
require_ex( "luacommon/object/player_t_guild_donation" )
require_ex( "luacommon/object/player_t_guild_pve" )
require_ex( "luacommon/object/player_t_prevent_kill_cheat" )
require_ex( "luacommon/object/player_t_customer_service" )
require_ex( "luacommon/object/player_t_god_divination" )
require_ex( "luacommon/object/player_t_red" )
require_ex( "luacommon/object/player_t_share" )
require_ex( "luacommon/object/player_t_level_reward" )
require_ex( "luacommon/object/player_t_pet" )
require_ex( "luacommon/object/player_t_celebration" )
require_ex( "luacommon/object/player_t_holiday_signin_award" )
require_ex( "luacommon/object/player_t_chat" )
require_ex( "luacommon/object/player_t_monthly_signin_award" )
require_ex( "luacommon/object/player_t_mall" )
require_ex( "luacommon/object/player_t_daily_online_award" )
require_ex( "luacommon/object/player_t_cycled_recharge_award" )
require_ex( "luacommon/object/player_t_growth_fund" )
require_ex( "luacommon/object/player_t_login_activity" )
require_ex( "luacommon/object/player_t_team_ladder" )
require_ex( "luacommon/object/player_t_parchment" )
require_ex( "luacommon/object/player_t_sanding" )
require_ex( "luacommon/object/player_t_survey" )
require_ex( "luacommon/object/player_t_small_data" )
require_ex( "luacommon/object/player_t_battle_justice" )
require_ex( "luacommon/object/player_t_hall" )
require_ex( "luacommon/object/player_t_level_recharge" )
require_ex( "luacommon/object/player_t_like" )
require_ex( "luacommon/object/player_t_carnival" )
require_ex( "luacommon/object/player_t_one_gold_lucky_draw" )
require_ex( "luacommon/object/player_t_egg" )
require_ex( "luacommon/object/player_t_festival" )
require_ex( "luacommon/object/player_t_player_chat_gift" )
require_ex( "luacommon/object/player_t_christmas_sell" )
require_ex( "luacommon/object/player_t_christmas_recharge_lucky_draw" )
require_ex( "luacommon/object/player_t_wing_system" )
require_ex( "luacommon/object/player_t_activity" )
require_ex( "luacommon/object/player_t_vip_reward" )
require_ex( "luacommon/object/player_t_resource_magnate" )
require_ex( "luacommon/object/player_t_group_buy" )
require_ex( "luacommon/object/player_t_resource_fund" )
require_ex( "luacommon/object/player_t_soulcard" )
--$PLAYER_MODULE

require_ex( "luacommon/instance/instance_t_const")

require_ex( "luacommon/object/player_t" )
require_ex( "luacommon/login_code" )
require_ex( "luacommon/s_cache" )

require_ex( "luacommon/item/item_t_use" )
require_ex( "luacommon/item/item_t_rouleau")
require_ex( "luacommon/item/item_t_buff" )
require_ex( "luacommon/item/item_t_reborn" )
require_ex( "luacommon/item/item_t_awake" )
require_ex( "luacommon/item/item_t_rune")
require_ex( "luacommon/item/item_t_stone")
require_ex( "luacommon/item/item_t_inherit")
require_ex( "luacommon/item/item_t_refine" )
require_ex( "luacommon/item/item_t_magic" )
require_ex( "luacommon/item/item_t_decompose" )
require_ex( "luacommon/item/item_t_skillbook" )
require_ex( "luacommon/item/item_t_orange" )
require_ex( "luacommon/item/item_t_equip_gs" )
require_ex( "luacommon/item/item_t_equip" )
require_ex( "luacommon/item/item_t_warehouse" )
require_ex( "luacommon/item/item_t_const" )
require_ex( "luacommon/item/item_t_soulcard" )
require_ex( "luacommon/item/item_t" )
require_ex( "luacommon/item/bag_t_warehouse" )
require_ex( "luacommon/item/bag_t" )

require_ex( "luacommon/mail/mail_t" )
require_ex( "luacommon/mail/mail_box_t" )

require_ex( "luacommon/friend/friend_const" )
require_ex( "luacommon/friend/friend_mng_core" )
require_ex( "luacommon/friend/friend_mng_db" )
require_ex( "luacommon/friend/friend_t" )
require_ex( "luacommon/friend/friend_set_t" )
require_ex( "luacommon/friend/friend_history_t" )
require_ex( "luacommon/friend/friend_history_list_t" )
require_ex( "luacommon/chat/chat_msg_t" )

require_ex( "luacommon/auction/auction_item_t" )
require_ex( "luacommon/trade/trade_item_t" )

WORLD_CONFIG = require_ex("luacommon/setting/resource/world_config")
CITY_SPAWN_POS_CONFIG = require_ex("luacommon/setting/CITY_SPAWN_POS_CONFIG")
require_ex( "luacommon/city/channel_mng" )

require_ex( "luacommon/gm_cmd" )
require_ex( "luacommon/net/gmclient" )
require_ex( "luacommon/rank_list/rank_common" )
require_ex( "luacommon/rank_list/rank_info_t" )
require_ex( "luacommon/rank_list/team_rank_info_t" )
require_ex( "luacommon/rank_list/team_champion_rank_info_t" )
require_ex( "luacommon/rank_list/guild_rank_info_t" )

require_ex( "net/dbserver" )
require_ex( "logic/db_shop" )
require_ex( "logic/db_gold_exchange" )
require_ex( "logic/db_bag" )
require_ex( "logic/db_soulcard" )
require_ex( "logic/db_random_names" )
require_ex( "logic/db_login" )
require_ex( "logic/db_skill" )
require_ex( "logic/db_element" )
require_ex( "logic/db_rune" )
require_ex( "logic/db_quest")
require_ex( "logic/db_avatar" )
require_ex( "logic/db_soul" )
require_ex( "logic/db_mastery" )
require_ex( "logic/db_pray" )
require_ex( "logic/db_pray_system" )
require_ex( "logic/db_mail" )
require_ex( "logic/db_time" )
require_ex( "logic/db_newbie_guide")
require_ex( "logic/db_system_data")
require_ex( "logic/db_mystic" )
require_ex( "luacommon/splus_sdk/order_mng" )
require_ex( "logic/db_order" )
require_ex( "logic/db_tower" )
require_ex( "logic/db_palace" )
require_ex( "luacommon/event/event_honor_hall/honor_hall_rank")
require_ex( "luacommon/event/event_honor_hall/honor_ladder_game")
require_ex( "logic/db_honor_hall" )
require_ex( "logic/db_attend" )
require_ex( "logic/db_daily_goals")
require_ex( "logic/db_rmb" )
require_ex( "logic/db_time_event" )
require_ex( "logic/db_gm" )
require_ex( "logic/db_rank" )
require_ex( "logic/db_guild_system" )
require_ex( "logic/db_player_offline_op" )
require_ex( "logic/db_snapshot" )
require_ex( "logic/db_guild" )
require_ex( "logic/db_inst" )
require_ex( "logic/db_friend" )
require_ex( "logic/db_guild_profession" )
require_ex( "logic/db_truncheon" )
require_ex( "logic/db_equip_exchange_shop" )
require_ex( "logic/db_permanent_attr_record" )
require_ex( "logic/db_title" )
require_ex( "logic/db_welfare" )
require_ex( "logic/db_trade" )
require_ex( "logic/db_guild_daily_pvp" )
require_ex( "logic/db_vip" )
require_ex( "logic/db_auction" )
require_ex( "logic/db_trade_statistic" )
require_ex( "logic/db_guild_donation" )
require_ex( "logic/db_guild_pve" )
require_ex( "logic/db_guild_weekend_battle" )
require_ex( "logic/db_prevent_kill_cheat" )
require_ex( "logic/db_customer_service" )
require_ex( "logic/db_god_divination" )
require_ex( "logic/db_red" )
require_ex( "logic/db_share" )
require_ex( "logic/db_level_reward" )
require_ex( "logic/db_pet" )
require_ex( "logic/db_celebration" )
require_ex( "logic/db_holiday_signin_award" )
require_ex( "logic/db_chat" )
require_ex( "logic/db_monthly_signin_award" )
require_ex( "logic/db_mall" )
require_ex( "logic/db_daily_online_award" )
require_ex( "logic/db_cycled_recharge_award" )
require_ex( "logic/db_growth_fund" )
require_ex( "logic/db_login_activity" )
require_ex( "logic/db_ladder_team" )
require_ex( "logic/db_player_team_ladder" )
require_ex( "logic/db_system_global_data" )

require_ex( "logic/db_sanding" )
require_ex( "logic/db_survey" )
require_ex( "logic/db_small_data" )
require_ex( "logic/db_battle_justice" )
require_ex( "logic/db_hall" )
require_ex( "logic/db_hall_mng" )
require_ex( "logic/db_level_recharge" )
require_ex( "logic/db_like" )
require_ex( "logic/db_ares_match" )
require_ex( "logic/db_honor_match" )
require_ex( "logic/db_rebate_generate" )
require_ex( "logic/db_carnival" )
require_ex( "logic/db_one_gold_lucky_draw" )
require_ex( "logic/db_egg" )
require_ex( "logic/db_festival" )
require_ex( "logic/db_player_chat_gift" )
require_ex( "logic/db_christmas_sell" )
require_ex( "logic/db_christmas_recharge_lucky_draw" )
require_ex( "logic/db_wing_system" )

require_ex( "logic/db_arena" )
require_ex( "logic/db_activity" )
require_ex( "logic/db_vip_reward" )
require_ex( "logic/db_activity_resource_magnate" )
require_ex( "logic/db_activity_group_buy" )
require_ex( "logic/db_activity_resource_fund" )
require_ex( "logic/db_item_log" )

require_ex( "logic/db_migrate" )
require_ex( "logic/db_online_num" )
--$DB_MODULE

require_ex( "luacommon/team/team_t" )

require_ex( "luacommon/timer/timers" )
require_ex( "timer/timers" )

require_ex( "luacommon/time_event/time_event_log_handle_reset" )

require_ex( "luacommon/object/event_mng" )
require_ex( "luacommon/activity/activity_mng" )

db_player_offline_op.do_start_delete_offline_timer()
time_event_log_handle_reset.init()



