
--[[
--  const type: nil, boolean, number, string
--]]

-- set cfg table empty to turn off opt_const 
-- cfg should not be changed by user(compiler only). 
local cfg =
{
    -- resmng
    [1] = 
    {
        const_keys = 
        { 
            -- STATE
            STATE_NONE      = true,
            STATE_SIT       = true,
            STATE_MELEE_ATK = true,
            STATE_SKILLING  = true,
            STATE_RUSH      = true,
            STATE_FSKILLING = true,
            STATE_FCASTING  = true,
            STATE_STAND_G   = true,
            STATE_STAND_F   = true,
            STATE_STUN      = true,
            STATE_FALL      = true,
            STATE_JUMP      = true,
            STATE_MOVE_G    = true,
            STATE_MOVE_F    = true,
            STATE_MOVE_TO   = true,
            STATE_TRANSFORM = true,
            STATE_AIRBOAT   = true,
            STATE_SNEAK     = true,
            STATE_FREEZE    = true,
            STATE_CHAOS     = true,
            STATE_PUSH      = true,
            STATE_MOTION    = true,
            STATE_DAMAGE    = true,
            STATE_FLY       = true,
            STATE_GROUND    = true,
            STATE_COMBAT    = true,
            STATE_DEAD      = true,
            STATE_COLLECT   = true,
            STATE_TRADE     = true,
            STATE_LINK      = true,
            STATE_NAVIGATE  = true,
            STATE_QUIZ      = true,
            STATE_MAX       = true,    
            STATE_GUARD     = true,
            STATE_CROSSTALK = true,
            -- MSG
            SYS_SET_STATE   = true,
            SYS_DEL_STATE   = true,
            MSG_INITIAL     = true,
            MSG_DESTROY     = true,
            MSG_GO_TOP      = true,
            MSG_UPDATE      = true,
            MSG_SETDATA     = true,
            MSG_RESET       = true,
            MSG_GETDATA     = true, 
            MSG_USER        = true, 
            MSG_STAND_UP    = true,
            MSG_SIT_DOWN    = true, 
            MSG_BE_PUSH     = true,
            MSG_START       = true,
            MSG_STOP        = true,
            MSG_OVER        = true,
            MSG_CHANGE_RANGE= true,
            MSG_ASK_SKILL   = true,
            MSG_HIT         = true,
            MSG_BUFF        = true,
            MSG_COLLECT     = true,
            MSG_PICKUP      = true,
            MSG_DOPICKUP    = true,
            MSG_MARKPOS     = true,
            MSG_ADDSKILL    = true,
            MSG_DELSKILL    = true,
            MSG_REVIVAL     = true,
            MSG_IALINK      = true,     
            MSG_NEXTPOINT   = true,
            MSG_ADV_STA_RECOVER	= true,
            MSG_AUTO_ASSIGN = true,
            MSG_SET_SPEED   = true,
            MSG_GAME_TIP    = true,
            MSG_VOBJ        = true,
            MSG_FLYHEIGHT   = true,
            MSG_WORLD_GONE  = true,
            MSG_SETSCALE    = true,
            MSG_LINK        = true,
            MSG_TRIGGER     = true,
            MSG_SHIPSTOP    = true,
            MSG_GRASS       = true,
            MSG_REPLACE     = true,
            MSG_CANNON      = true,
            MSG_RESPAWN     = true,
            -- ATK
            AF_GENERIC		= true,
            AF_MISS			= true,
            AF_CRITICAL		= true,
            AF_RESIST		= true,
            AF_PASS         = true,
            -- ATTR
            MZONE = true,
            AZONE = true,
            SZONE = true,
            HP = true,
            MP = true,
            GP = true,
            SGOLD = true,
            EP = true,
            LV = true,
            GOLD = true,
            FLV = true,
            FEP = true,
            VIT = true,
            MONEY = true,
            EP2 = true,
            FHP = true,
            FMP = true,
            ADJUST = true,
            DATA_ONLY = true,
            MAXHP = true,
            MAXMP = true,
            ATK_MELEE = true,
            ATK_MAGIC = true,
            DEF_MELEE = true,
            DEF_MAGIC = true,
            PAR_MELEE = true,
            PAR_MAGIC = true,
            HIT_MELEE = true,
            HIT_MAGIC = true,
            CRI_MELEE = true,
            CRI_MAGIC = true,
            ATK_SPEED = true,
            RECOVER_HP = true,
            RECOVER_MP = true,
            DATA_FUNC = true,
            STR = true,
            DEX = true,
            STA = true,
            SPI = true,
            INT = true,
            MELEE_DMG_DEC = true,
            MAGIC_DMG_DEC = true,
            BLOCK_DAMAGE = true,
            MOVE_SPEED = true,
            MELEE_DMG_DEC_RATE = true,
            MAGIC_DMG_DEC_RATE = true,
            IMMU_ESP_SKILL_RATE = true,
            COUNTER_STRIKE = true,
            NO_SNEAK = true,
            LOOP_SKILL_RATE     = true,
            LOOP_SKILL_DEC_TIME = true,
            PET_MOOD_DEC_RATE   = true,
            PET_HP_DEC_RATE     = true,
            UNDMG               = true,
            ITEM_MAXHP          = true,
            VICE_ATK            = true,
            UNDIE               = true,
            ADJ_DMG_MELEE = true,
            ADJ_DMG_MAGIC = true,
            VICE_ATK_POW = true,
            ITEM_ATK_MELEE = true,
            ITEM_ATK_MAGIC = true,
            ITEM_DEF_MELEE = true,
            ITEM_DEF_MAGIC = true,
            CONSUME_ADJ = true,
            EXP_RATE_ADD = true,
            DROPGOLD_RATE_ADD = true,
            DROPITEM_RATE_ADD = true,
            ATKDMG_RATE_ADD = true,
            SKILLCOOLTIME_RATE_ADD = true,
            DMG_HP_ADD  = true,
            DMG_MP_ADD  = true,
            ENMITY_MELEE_RATE_ADD = true,
            ONEKILLING = true,
            SNEAK = true,
            FLY_SPEED = true,
            FLY_HEIGHT = true,
            ACC_TIME = true,
            ENMITY   = true,
            COUNTER_MSTRIKE  = true,
            FMAXHP = true,
            FMAXMP = true,
            FATK   = true,
            FDEF   = true,
            FSHD   = true,
            FBAT   = true,
            ITEM_FATK   =  true, 
            ITEM_FDEF   =  true,
            ITEM_FSHD   =  true,
            FHIT    = true,
            FPAR    = true,
            ITEM_FHIT   = true,
            ITEM_FPAR   = true,
            CRI_MELEE_DMG_ADD_RATE  = true,
            CRI_MAGIC_DMG_ADD_RATE  = true,
            CRI_MELEE_DMG_DEC_RATE  = true,
            CRI_MAGIC_DMG_DEC_RATE  = true,
            CRI_MELEE_RESIST_RATE   = true,
            CRI_MAGIC_RESIST_RATE   = true,
            MELEE_ARMOR_PENE        = true,
            MAGIC_ARMOR_PENE        = true,
            -- 特殊抗性
            RESIST_STUN			= true,
            RESIST_FREEZE		= true,
            RESIST_CHAOS		= true,
            RESIST_MELEE		= true,
            RESIST_MAGIC		= true,
            RESIST_PUSH			= true,
            RESIST_RECOVER      = true,
            RESIST_PULL         = true,
            -- buff group
            GROUP_ACTIVE_SKILL_ATK  = true,
            GROUP_ACTIVE_SKILL_DEF  = true,
            GROUP_DAMAGE_TO_HP      = true,
            GROUP_HI_HP_ADD_DAMAGE  = true,
            GROUP_LO_HP_ADD_DAMAGE  = true,
            GROUP_REFILL_BY_TARGET_DEAD = true,
            GROUP_MP_REPLACE_HP     = true,
            GROUP_IMMU_SKILL        = true,
            GROUP_ABSORB_DAMAGE     = true,
            GROUP_MON_NO_RECOVER_HP = true,
            GROUP_IGNORE_DEF        = true,
            GROUP_UP_SKILL_LV       = true,
            GROUP_DAMAGE_TO_MP      = true,
            GROUP_ACTIVE_SKILL_ATK_BY_SKILL = true,
            GROUP_AUTO_ATK          = true,
            GROUP_RATE_DAMAGE       = true,
            GROUP_BLOCK_DAMAGE_ONCE = true,
            GROUP_SILENCE           = true,
            GROUP_SNEAK_DAMAGE      = true,
            GROUP_CONTINUE_DAMAGE   = true,
            GROUP_IMMU_BUFF         = true,
            GROUP_IMMU_ESP_SKILL    = true,
            GROUP_UNDIE             = true,
            GROUP_CONTINUE_RATE_DAMAGE  = true,
            --宠物专用Buff
            GROUP_RATE_BLOCK_CRITICAL_DMG = true,
            GROUP_IMMU_BUFF_BY_ID         = true,
            GROUP_PET_CONTINUE_DAMAGE     = true,
            GROUP_FINDMONSTER             = true,
            GROUP_ACTIVE_EFFECT           = true,
            GROUP_IMMU_BREAKING           = true,
            G_POTION_HP     = true,
            G_POTION_MP     = true,
            G_POTION_MPHP   = true,
            GROUP_ANTIINTERFERE = true,
            GROUP_ANTIIMMOBILIZE = true,
            GROUP_ANTISCALE = true,
            GROUP_ANTITRANSFORM = true,
            GROUP_FLYSPEEDDOWN = true,
            GROUP_FLYIMMOBILIZE = true,
            GROUP_FLYSCALE = true,
            GROUP_FLYSPEEDUP = true,
            GROUP_FLYSNEAK = true,
            GROUP_FLYBLOCK = true,
            GROUP_FLYREFLECT = true,
            GROUP_FLYINVINCIBLE = true,
            GROUP_AIRBOAT_BLOCK_DAMAGE_ONCE = true,
            ADD_ENMITY_T_VIEW			= true,
            ADD_ENMITY_T_MELEE			= true,
            ADD_ENMITY_T_SKILL			= true,
            ADD_ENMITY_T_RECOVER		= true,
            ADD_ENMITY_T_ADD			= true,
            ADD_ENMITY_T_RANGE			= true,
            ADD_ENMITY_T_HIT			= true,
            ADD_ENMITY_T_PERCENT        = true,
            ADD_ENMITY_T_TEAM           = true,
            -- some hardcode
            MI_WENHEQIWEI = true,
            EVE_GUARD_LIST = true,
            WI_WORLD_FAMILYPK = true,
            -- battle
            CLASS_RESOURCE = true,
            LEVEL_LIMIT_COLLECT = true,
            RA_SAFETY = true,
            RA_FIGHT = true,
            RA_DAMAGE = true,
            RA_PK = true,
            RA_SCHOOL = true,
            PK_NAME_WHITE                         = true,
            PK_NAME_GRAY                          = true,
            PK_NAME_BLACK                         = true,
            PK_NAME_RED                           = true,
            NULL_ID = true,
            AIMSG_DAMAGE = true,	
        },
        is_parent = function( t )
            return t == _G.resmng 
        end
    },
}


local opt_const = 
{
    -- const keys finder
    get_const_keys = function( t, opt_lv )
        if opt_lv >= 3 then
            for i, v in ipairs( cfg ) do
                if v.is_parent( t ) then
                    return i, v.const_keys
                end
            end
        end
        return nil, nil
    end,

    -- get cfg 
    get_const_cfg = function()
        return cfg
    end,

    -- opt begin
    -- create const_state 
    begin_const_state = function()
        local stmap = {}
        for i, v in ipairs( cfg ) do
            stmap[i] = {}
        end
        return stmap
    end,

    -- opt finish
    -- do nothing
}

return opt_const
