
function require_ex( _mname )
    package.loaded[_mname] = nil
    return require( _mname )    
end

------------------------------------------------------------------------------------------
--                              初始化LuaJIT
------------------------------------------------------------------------------------------
if g_debug then
    package.path = "./?.lua;./?.lc"
else
    --package.path = "./?.lc"
    package.path = "./?.lc"
end

require_ex( "jit/opt" ) 

if g_debug then
    if jit then
        jit.debug(2)
        jit.opt.start(3)
        c_log( "++++++++++++++++++LUAJIT(v1) DEBUG OPT LEVEL 3+++++++++++++++++++" )
    end
else
    if jit then
        jit.debug(0)
        jit.opt.start(3)
        c_log( "++++++++++++++++++LUAJIT(v1) RELEASE OPT LEVEL 3+++++++++++++++++++" )
    end
end

math.randomseed( os.time() )
------------------------------------------------------------------------------------------
--                              加载所有模块
------------------------------------------------------------------------------------------
require_ex( "luacommon/limit" )
require_ex( "luacommon/msg" )
require_ex( "luacommon/utils" )
require_ex( "luacommon/login_code" )
require_ex( "luacommon/math3d" )

-- sys configable const 
GLOBAL_DATA_CONFIG = require_ex( "luacommon/setting/GLOBAL_DATA_CONFIG" )
GOBLIN_MARKET_CONFIG = require_ex( "luacommon/setting/GOBLIN_MARKET_CONFIG" )
PRAY_SYS_CONFIG = require_ex( "luacommon/setting/PRAY_SYS_CONFIG" )
RECHARGE_ITEM_LIST = require_ex( "luacommon/setting/RECHARGE_ITEM_LIST" )
RECHARGE_VIP_CONFIG = require_ex( "luacommon/setting/RECHARGE_VIP_CONFIG" )
GM_CMD_CFG = require_ex( "luacommon/setting/GM_CMD_CFG" )
NEWBIE_GUIDE_CONFIG = require_ex( "luacommon/setting/NEWBIE_GUIDE_CONFIG" )
ENERGY_CONFIG = require_ex( "luacommon/setting/ENERGY_CONFIG" )
RECHARGE_AWARD_CONFIG = require_ex(  "luacommon/setting/RECHARGE_AWARD_CONFIG" )
AWARD_CONSUME_CONFIG = require_ex(  "luacommon/setting/AWARD_CONSUME_CONFIG" )
ELAMITE_TEMPLE_CONFIG = require_ex(  "luacommon/setting/ELAMITE_TEMPLE_CONFIG" )
NPC_INTERACTION_CONFIG = require_ex( "luacommon/setting/NPC_INTERACTION_CONFIG" )
NPC_INTERACTIVE_CONTENT_CONFIG = require_ex( "luacommon/setting/NPC_INTERACTIVE_CONTENT_CONFIG" )
INSTANCE_CFG = require_ex("luacommon/setting/INSTANCE_CFG")
ACTIVITY_INSTANCE_CONFIG = require_ex("luacommon/setting/ACTIVITY_INSTANCE_CONFIG")
MYSTIC_GOODS_CONFIG = require_ex( "luacommon/setting/MYSTIC_GOODS_CONFIG" )
MYSTIC_SYS_CONFIG = require_ex( "luacommon/setting/MYSTIC_SYS_CONFIG" )
TALENT = require_ex( "luacommon/setting/TALENT" )
TALENT_UPGRADE = require_ex( "luacommon/setting/TALENT_UPGRADE" )
TALENT_UNLOCK = require_ex( "luacommon/setting/TALENT_UNLOCK" )
SKILL_UNLOCK = require_ex( "luacommon/setting/SKILL_UNLOCK" )
TEAM_SKILL_UNLOCK = require_ex( "luacommon/setting/TEAM_SKILL_UNLOCK" )
SKILL_LEARN = require_ex( "luacommon/setting/SKILL_LEARN" )
TEAM_SKILL_LEARN = require_ex( "luacommon/setting/TEAM_SKILL_LEARN" )
SKILL_LEVELUP = require_ex( "luacommon/setting/SKILL_LEVELUP" )
SKILL_DESC_PARAMS = require_ex( "luacommon/setting/SKILL_DESC_PARAMS" )
DAILY_GOALS = require_ex( "luacommon/setting/DAILY_GOALS" )
HOLIDAY_EVENT_CONFIG = require_ex( "luacommon/setting/HOLIDAY_EVENT_CONFIG" )
HOLIDAY_EVENT_SYS_CONFIG = require_ex( "luacommon/setting/HOLIDAY_EVENT_SYS_CONFIG" )
TIME_EVENT = require_ex( "luacommon/setting/TIME_EVENT" )
EVENT_CALENDAR_CONFIG = require_ex( "luacommon/setting/EVENT_CALENDAR" )
RUNNER_CONFIG = require_ex( "luacommon/setting/RUNNER_CONFIG" )
RUNNER_NPC_CONFIG = require_ex( "luacommon/setting/RUNNER_NPC_CONFIG" )
RUNNER_ITEM_CONFIG = require_ex( "luacommon/setting/RUNNER_ITEM_CONFIG" )
RUNNER_NPC_BUY_CONFIG = require_ex( "luacommon/setting/RUNNER_NPC_BUY_CONFIG" )
RUNNER_NPC_SELL_CONFIG = require_ex( "luacommon/setting/RUNNER_NPC_SELL_CONFIG" )
CLIENT_ACCESS_SWITCH = require_ex( "luacommon/setting/CLIENT_ACCESS_SWITCH" )
LEONA_GIFT_CONFIG = require_ex( "luacommon/setting/LEONA_GIFT_CONFIG" )
ORANGE_EQUIP_GRADE_CONFIG = require_ex( "luacommon/setting/ORANGE_EQUIP_GRADE_CONFIG" )
ORANGE_EQUIP_EXCHANGE_CONFIG = require_ex( "luacommon/setting/ORANGE_EQUIP_EXCHANGE_CONFIG" )
ORANGE_EQUIP_ASCEND_CONFIG = require_ex( "luacommon/setting/ORANGE_EQUIP_ASCEND_CONFIG" )
ORANGE_EQUIP_ASCEND_MATERIAL = require_ex( "luacommon/setting/ORANGE_EQUIP_ASCEND_MATERIAL" )
ELAM_MILITARY_SUPPLIES_CFG = require_ex( "luacommon/setting/ELAM_MILITARY_SUPPLIES_CFG" )
SKILL_BOOK_COMPOUND_CONFIG = require_ex( "luacommon/setting/SKILL_BOOK_COMPOUND" )
TEAM_INST_CONFIG = require_ex( "luacommon/setting/TEAM_INST_CONFIG" )
GUILD_CAMPFIRE_CONFIG = require_ex( "luacommon/setting/GUILD_CAMPFIRE_CONFIG" )
PVP_MAIN_UI_CONFIG = require_ex( "luacommon/setting/PVP_MAIN_UI" )

AVATAR_COMMON_CONFIG = require_ex( "luacommon/setting/AVATAR_COMMON_CONFIG" )
AVATAR_MODEL_CONFIG = require_ex( "luacommon/setting/AVATAR_MODEL_CONFIG" )
AVATAR_ASCEND_LEVEL_CONFIG = require_ex( "luacommon/setting/AVATAR_ASCEND_LEVEL_CONFIG" )
AVATAR_ASCEND_STAR_CONFIG = require_ex( "luacommon/setting/AVATAR_ASCEND_STAR_CONFIG" )
AVATAR_ATTR_CONFIG = require_ex( "luacommon/setting/AVATAR_ATTR_CONFIG" )
AVATAR_LEVEL_ATTRID_CONFIG = require_ex( "luacommon/setting/AVATAR_LEVEL_ATTRID_CONFIG" )
AVATAR_LEVEL_ATTRVAL_CONFIG = require_ex( "luacommon/setting/AVATAR_LEVEL_ATTRVAL_CONFIG" )
AVATAR_ULTI_SKILL_CONFIG = require_ex( "luacommon/setting/AVATAR_ULTI_SKILL_CONFIG" )
AVATAR_BUFF_SKILL_CONFIG = require_ex( "luacommon/setting/AVATAR_BUFF_SKILL_CONFIG" )
AVATAR_STAR_BENEFIT_CONFIG = require_ex( "luacommon/setting/AVATAR_STAR_BENEFIT_CONFIG" )
AVATAR_MED_ASCEND_STAR_CONFIG = require_ex( "luacommon/setting/AVATAR_MED_ASCEND_STAR_CONFIG" )
AVATAR_MED_SKILL_CONFIG = require_ex( "luacommon/setting/AVATAR_MED_SKILL_CONFIG" )
AVATAR_MED_BUFF_SKILL_CONFIG = require_ex( "luacommon/setting/AVATAR_MED_BUFF_SKILL_CONFIG" )
AVATAR_MED_ATTR_SKILL_CONFIG = require_ex( "luacommon/setting/AVATAR_MED_ATTR_SKILL_CONFIG" )
AVATAR_MED_BUFF_RANDOM_CONFIG = require_ex( "luacommon/setting/AVATAR_MED_BUFF_RANDOM_CONFIG" )
AVATAR_MED_ATTR_RANDOM_CONFIG = require_ex( "luacommon/setting/AVATAR_MED_ATTR_RANDOM_CONFIG" )
AVATAR_GROUP_ATTR_CONFIG = require_ex( "luacommon/setting/AVATAR_GROUP_ATTR_CONFIG" )
AVATAR_MATERIAL_EXCHANGE_CONFIG = require_ex( "luacommon/setting/AVATAR_MATERIAL_EXCHANGE_CONFIG" )

--add by kent
AVATAR_RANK_UP_CONFIG = require_ex( "luacommon/setting/AVATAR_RANK_UP_CONFIG" )
AVATAR_RANK_UP_SKILL_CONFIG = require_ex( "luacommon/setting/AVATAR_RANK_UP_SKILL_CONFIG" )
ASTROLABE_CONFIG = require_ex( "luacommon/setting/ASTROLABE_CONFIGURE" )
--
--add by abel
PLAYER_AVATAR_EQUIPS = require_ex( "luacommon/setting/PLAYER_AVATAR_EQUIPS" )

SOUL_AVATAR_CONFIG = require_ex( "luacommon/setting/SOUL_AVATAR_CONFIG" )
SOUL_ATTR_CONFIG = require_ex( "luacommon/setting/SOUL_ATTR_CONFIG" )
SOUL_AWAKE_CONFIG = require_ex( "luacommon/setting/SOUL_AWAKE_CONFIG" )

GUILD_LEVEL_CONFIG = require_ex( "luacommon/setting/GUILD_LEVEL_CONFIG" )
GUILD_POPULARITY_CONFIG = require_ex( "luacommon/setting/GUILD_POPULARITY_CONFIG" )
GUILD_ROLE_PRIVILEGE_CONFIG = require_ex( "luacommon/setting/GUILD_ROLE_PRIVILEGE_CONFIG" )
GUILD_SYSTEM_CONFIG = require_ex( "luacommon/setting/GUILD_SYSTEM_CONFIG" )
GUILD_VICE_PROFESSION_CONFIG = require_ex( "luacommon/setting/GUILD_VICE_PROFESSION_CONFIG" )
GUILD_GOODS_CONFIG = require_ex( "luacommon/setting/GUILD_GOODS_CONFIG" )
GUILD_VICE_PROFESSION_LEVEL_CONFIG = require_ex( "luacommon/setting/GUILD_VICE_PROFESSION_LEVEL_CONFIG" )
GUILD_VICE_PROFESSION_EQUIP_CONFIG = require_ex( "luacommon/setting/GUILD_VICE_PROFESSION_EQUIP_CONFIG" )
GUILD_WELFARE_CONFIG = require_ex( "luacommon/setting/GUILD_WELFARE_CONFIG" )
GUILD_SCENE_CONFIG = require_ex( "luacommon/setting/GUILD_SCENE_CONFIG" )
GUILDPROF_TASK = require_ex( "luacommon/setting/GUILDPROF_TASK" )
GUILDPROF_TASK_PRIZE_CONFIG = require_ex( "luacommon/setting/GUILDPROF_TASK_PRIZE_CONFIG" )
GUILDPROF_TARGETS = require_ex( "luacommon/setting/GUILDPROF_TARGETS" )
GUILD_DONATION_CONFIG = require_ex( "luacommon/setting/GUILD_DONATION_CONFIG" )
GUILD_PVE_DIFF_CFG = require_ex( "luacommon/setting/GUILD_PVE_DIFF_CFG" )
GUILD_PVE_CONFIG = require_ex( "luacommon/setting/GUILD_PVE_CONFIG" )
GUILD_PVE_COST_CFG= require_ex( "luacommon/setting/GUILD_PVE_COST_CFG" )
GUILD_PVE_CONTRIBUTION = require_ex( "luacommon/setting/GUILD_PVE_CONTRIBUTION" )
GUILD_PVE_REWARD = require_ex( "luacommon/setting/GUILD_PVE_REWARD" )
GUILD_MAINTAIN_FEE_CONFIG = require_ex( "luacommon/setting/GUILD_MAINTAIN_FEE_CONFIG" )
PREVENT_KILL_CHEAT_CFG = require_ex( "luacommon/setting/PREVENT_KILL_CHEAT_CFG" )
CONTRIBUTION_MULTIRATE_CFG = require_ex( "luacommon/setting/CONTRIBUTION_MULTIRATE_CFG" )
GUILD_WEEKEND_BATTLE_CFG = require_ex( "luacommon/setting/GUILD_WEEKEND_BATTLE_CFG" )
GUILD_SHOP_CONFIG = require_ex( "luacommon/setting/GUILD_SHOP_CONFIG" )
MONSTER_TRANSFORM_LEVEL_MATCH_CFG = require_ex( "luacommon/setting/MONSTER_TRANSFORM_LEVEL_MATCH_CFG" )
GUILDPROF_TASK_SYS_CFG = require_ex( "luacommon/setting/GUILDPROF_TASK_SYS_CFG" )
SERVER_AND_CLIENT_TEXT_CONFIG = require_ex( "luacommon/setting/SERVER_AND_CLIENT_TEXT_CONFIG" )
EQUIP_RAND_ATTR_LIB_WITH_JOBS = require_ex( "luacommon/setting/EQUIP_RAND_ATTR_LIB_WITH_JOBS" )
GUILD_BOUTIQUE = require_ex( "luacommon/setting/GUILD_BOUTIQUE" )
GUILD_BOUTIQUE_ITEM_LIB = require_ex( "luacommon/setting/GUILD_BOUTIQUE_ITEM_LIB" )
GUILD_DALLY = require_ex( "luacommon/setting/GUILD_DALLY" )
GUILD_CONFIGURE_NUM = require_ex( "luacommon/setting/GUILD_CONFIGURE_NUM" )
GUILD_ACTIVITY_GIFT = require_ex( "luacommon/setting/GUILD_ACTIVITY_GIFT" )



TEAM_RECRUIT_CONFIG = require_ex( "luacommon/setting/TEAM_RECRUIT_CONFIG" )
GEAR_SCORE_GRADE_CONFIG = require_ex( "luacommon/setting/GEAR_SCORE_GRADE_CONFIG" )
LUCKY_RATE_CONFIG = require_ex( "luacommon/setting/LUCKY_RATE_CONFIG" )

GOD_DIVINATION_CONFIG = require_ex( "luacommon/setting/GOD_DIVINATION_CONFIG" )
GOD_DIVINATION_ASTROLABE_CONFIG = require_ex( "luacommon/setting/GOD_DIVINATION_ASTROLABE_CONFIG" )
GOD_DIVINATION_RUNE_CONFIG = require_ex( "luacommon/setting/GOD_DIVINATION_RUNE_CONFIG" )

RED_CONFIG = require_ex( "luacommon/setting/RED_CONFIG" )
RED_SYSTEM_CONFIG = require_ex( "luacommon/setting/RED_SYSTEM_CONFIG" )
RED_BULLETIN_CONFIG = require_ex( "luacommon/setting/RED_BULLETIN_CONFIG" )

PLAYER_ATTR = require_ex("luacommon/setting/PLAYER_ATTR")
COMPETITION_PVP_PLAYER_ATTR = require_ex("luacommon/setting/COMPETITION_PVP_PLAYER_ATTR")
ATTR_CONV_RATE = require_ex("luacommon/setting/ATTR_CONV_RATE")
require_ex("luacommon/setting/JOBS") 
TITLE = require_ex("luacommon/setting/TITLE")
WILDS = require_ex("luacommon/setting/WILDS") 
CINEMA_ACTIVATE_CHUNK = require_ex("luacommon/setting/CINEMA_ACTIVATE_CHUNK") 

ACTIVITY_LEVEL_REWARD_CONFIG = require_ex("luacommon/setting/ACTIVITY_LEVEL_REWARD_CONFIG") 
RECHARGE_ACTIVITY_CODE = require_ex("luacommon/setting/RECHARGE_ACTIVITY_CODE") 

PET_LEVEL_CONFIG = require_ex("luacommon/setting/PET_LEVEL_CONFIG")
PET_AVATAR_CONFIG = require_ex("luacommon/setting/PET_AVATAR_CONFIG")
PET_SHOWID_CONFIG = require_ex("luacommon/setting/PET_SHOWID_CONFIG")

HOLIDAY_SIGNIN_AWARD_GLOBAL_CONFIG = require_ex( "luacommon/setting/HOLIDAY_SIGNIN_AWARD_GLOBAL_CONFIG" )
HOLIDAY_SIGNIN_AWARD_CONFIG = require_ex( "luacommon/setting/HOLIDAY_SIGNIN_AWARD_CONFIG" )

MONTHLY_SIGNIN_AWARD_GLOBAL_CONFIG = require_ex( "luacommon/setting/MONTHLY_SIGNIN_AWARD_GLOBAL_CONFIG" )
MONTHLY_SIGNIN_AWARD_CONFIG = require_ex( "luacommon/setting/MONTHLY_SIGNIN_AWARD_CONFIG" )

MALL_PRODUCT_CONFIG = require_ex( "luacommon/setting/MALL_PRODUCT_CONFIG" )
MALL_TIME_CONFIG = require_ex( "luacommon/setting/MALL_TIME_CONFIG" )
MALL_PUBLIC_CONFIG = require_ex( "luacommon/setting/MALL_PUBLIC_CONFIG" )
DAILY_ONLINE_AWARD_CONFIG = require_ex( "luacommon/setting/DAILY_ONLINE_AWARD_CONFIG" )
CYCLED_RECHARGE_AWARD_CONFIG = require_ex( "luacommon/setting/CYCLED_RECHARGE_AWARD_CONFIG" )
GROWTH_FUND_CONFIG = require_ex( "luacommon/setting/GROWTH_FUND_CONFIG" )
GROWTH_FUND_GLOBAL_CONFIG = require_ex( "luacommon/setting/GROWTH_FUND_GLOBAL_CONFIG" )
LOGIN_ACTIVITY_CONFIG = require_ex( "luacommon/setting/LOGIN_ACTIVITY_CONFIG" )
DAY_AWARD = require_ex( "luacommon/setting/DAY_AWARD" )
DAY_QUEST = require_ex( "luacommon/setting/DAY_QUEST" )
HALF_PRICE_CONFIG = require_ex( "luacommon/setting/HALF_PRICE_CONFIG" )
MELT_SYSTEM_CONFIG = require_ex( "luacommon/setting/MELT_SYSTEM_CONFIG" )
CELEBRATION_REWARD_CONFIG = require_ex( "luacommon/setting/CELEBRATION_REWARD_CONFIG" )
CELE_LOTTERY_GOODS = require_ex( "luacommon/setting/CELE_LOTTERY_GOODS" )
CELE_LOTTERY_LEVEL = require_ex( "luacommon/setting/CELE_LOTTERY_LEVEL" )
CELE_LOTTERY_LEVEL_FIRST_TIME = require_ex("luacommon/setting/CELE_LOTTERY_LEVEL_FIRST_TIME")
CELE_SYS_CONFIG = require_ex( "luacommon/setting/CELE_SYS_CONFIG" )
CELE_INVEST_CONFIG = require_ex( "luacommon/setting/CELE_INVEST_CONFIG" )
FIRST_RECHARGE_AWARD = require_ex( "luacommon/setting/FIRST_RECHARGE_AWARD" )
INSTANCE_EXP_MULTIPLE_FACTOR = require_ex( "luacommon/setting/INSTANCE_EXP_MULTIPLE_FACTOR" )
SANDING_CONFIG = require_ex( "luacommon/setting/SANDING_CONFIG" )
GUILD_ROLE_WELFARE_GLOBAL_CONFIG = require_ex( "luacommon/setting/GUILD_ROLE_WELFARE_GLOBAL_CONFIG" )
GUILD_ROLE_RANK_AWARD_CONFIG = require_ex( "luacommon/setting/GUILD_ROLE_RANK_AWARD_CONFIG" )
GUILD_ROLE_PROTECT_CITY_AWARD_CONFIG = require_ex( "luacommon/setting/GUILD_ROLE_PROTECT_CITY_AWARD_CONFIG" )
GUILD_ROLE_FIGHT_AWARD_CONFIG = require_ex( "luacommon/setting/GUILD_ROLE_FIGHT_AWARD_CONFIG" )
GUILD_ROLE_ITEM_LIB_CONFIG = require_ex( "luacommon/setting/GUILD_ROLE_ITEM_LIB_CONFIG" )
RANDOM_MALE_NAMES = require_ex( "luacommon/setting/RANDOM_MALE_NAMES" )
RANDOM_FEMALE_NAMES = require_ex( "luacommon/setting/RANDOM_FEMALE_NAMES" )
RANDOM_SURNAMES = require_ex( "luacommon/setting/RANDOM_SURNAMES" )
ROBOT_GS_TO_ATTR_DIFF_CFG = require_ex( "luacommon/setting/ROBOT_GS_TO_ATTR_DIFF_CFG" )
PARCHMENT_CONFIG = require_ex( "luacommon/setting/PARCHMENT_CONFIG" )
RECHARGE_BIG_AWARD_CONFIG = require_ex( "luacommon/setting/RECHARGE_BIG_AWARD_CONFIG" )
TOWER_RANK_AWARD_CONFIG = require_ex( "luacommon/setting/TOWER_RANK_AWARD_CONFIG" )
LOTTERY_MALL_CONFIG = require_ex( "luacommon/setting/LOTTERY_MALL_CONFIG" )
HALL_UPVOTE_REWARD_CONFIG = require_ex( "luacommon/setting/HALL_UPVOTE_REWARD_CONFIG" )
LEVEL_RECHARGE_ITEM_GIFT_GLOBAL_CONFIG = require_ex( "luacommon/setting/LEVEL_RECHARGE_ITEM_GIFT_GLOBAL_CONFIG" )
LEVEL_RECHARGE_ITEM_GIFT = require_ex( "luacommon/setting/LEVEL_RECHARGE_ITEM_GIFT" )
EVENT_CARNIVAL_CONFIG = require_ex( "luacommon/setting/EVENT_CARNIVAL_CONFIG" )
ONE_GOLD_LUCKY_DRAW_GOODS_CONFIG = require_ex( "luacommon/setting/ONE_GOLD_LUCKY_DRAW_GOODS_CONFIG" )
ONE_GOLD_LUCKY_DRAW_GLOBAL_CONFIG = require_ex( "luacommon/setting/ONE_GOLD_LUCKY_DRAW_GLOBAL_CONFIG" )
CHAPTER_CONFIG = require_ex( "luacommon/setting/CHAPTER_CONFIG" )
RECHARGE_ENTICE_CONTENT_CONFIG = require_ex( "luacommon/setting/RECHARGE_ENTICE_CONTENT_CONFIG" )
RECHARGE_ENTICE_LEVEL_CONFIG = require_ex( "luacommon/setting/RECHARGE_ENTICE_LEVEL_CONFIG" )
EGG_GLOBAL_CONFIG = require_ex( "luacommon/setting/EGG_GLOBAL_CONFIG" )
EGG_MON_CONFIG = require_ex( "luacommon/setting/EGG_MON_CONFIG" )
EGG_MON_REWARD_CONFIG = require_ex( "luacommon/setting/EGG_MON_REWARD_CONFIG" )
EGG_NPC_CONFIG = require_ex( "luacommon/setting/EGG_NPC_CONFIG" )
EGG_NPC_POS_CONFIG = require_ex( "luacommon/setting/EGG_NPC_POS_CONFIG" )
EGG_FEED_EVENT_CONFIG = require_ex( "luacommon/setting/EGG_FEED_EVENT_CONFIG" )
EGG_TYPE_CONFIG = require_ex( "luacommon/setting/EGG_TYPE_CONFIG" )
EGG_NUTRIENT_CONFIG = require_ex( "luacommon/setting/EGG_NUTRIENT_CONFIG" )
EGG_QUALITY_CONFIG = require_ex( "luacommon/setting/EGG_QUALITY_CONFIG" )
ONE_GOLD_LUCKY_DRAW_BONUS_GOODS_CONFIG = require_ex( "luacommon/setting/ONE_GOLD_LUCKY_DRAW_BONUS_GOODS_CONFIG" )
FESTIVAL_SYSTEM_CONFIG = require_ex( "luacommon/setting/FESTIVAL_SYSTEM_CONFIG" )
CHAT_GIFT_GLOBAL_CONFIG = require_ex( "luacommon/setting/CHAT_GIFT_GLOBAL_CONFIG" )
CHRISTMAS_SELL_GLOBAL_CONFIG = require_ex( "luacommon/setting/CHRISTMAS_SELL_GLOBAL_CONFIG" )
CHRISTMAS_RECHARGE_LUCKY_DRAW_GLOBAL_CONFIG = require_ex( "luacommon/setting/CHRISTMAS_RECHARGE_LUCKY_DRAW_GLOBAL_CONFIG" )
CHRISTMAS_SELL_ITEM_CONFIG = require_ex( "luacommon/setting/CHRISTMAS_SELL_ITEM_CONFIG" )
WING_UPGRADE_CONFIG = require_ex( "luacommon/setting/WING_UPGRADE_CONFIG" )
WING_CONFIG = require_ex( "luacommon/setting/WING_CONFIG" )

WING_CORE_UPGRADE_STAR = require_ex( "luacommon/setting/WING_CORE_UPGRADE_STAR") 
WING_SKILL_RANKS = require_ex( "luacommon/setting/WING_SKILL_RANKS")    
WING_SKILLS = require_ex( "luacommon/setting/WING_SKILLS")
WING_CORE_ATTRS = require_ex( "luacommon/setting/WING_CORE_ATTRS")
WING_CORES = require_ex( "luacommon/setting/WING_CORES")

ARENA_RANK = require_ex( "luacommon/setting/ARENA_RANK")
ARENA_RANK_ROBOT = require_ex( "luacommon/setting/ARENA_RANK_ROBOT")
ARENA_SETTING = require_ex( "luacommon/setting/ARENA_SETTING" )

EMA_GIFT = require_ex( "luacommon/setting/EMA_GIFT" )
--ARENA_RANK_BUY = require_ex( "luacommon/setting/ARENA_RANK_BUY")

ACTIVITY_VIP_REWARD_CONFIG = require_ex( "luacommon/setting/ACTIVITY_VIP_REWARD_CONFIG" )

--$SETTING_FILES

require_ex( "luacommon/quest/target_type")
require_ex( "luacommon/share/share_const" )
require_ex( "luacommon/share/share_func" )
--require_ex( "luacommon/share/class_base" )
require_ex( "luacommon/module/event_mgr_t" )
CINEMA_CFG = require_ex("luacommon/setting/CINEMA_CFG") 
require_ex( "luacommon/module/cinema_mgr" )
require_ex( "luacommon/formula/player_attr" )
require_ex( "luacommon/formula/fight_action" )
require_ex( "luacommon/object/shop_t" )
require_ex( "object/shop_mng" )
require_ex( "luacommon/object/shop_mng" )
require_ex( "luacommon/object/gold_exchange_t" )
require_ex( "object/gold_exchange_mng" )
require_ex( "luacommon/object/gold_exchange_mng" )
require_ex( "luacommon/event/competition_pvp_player_attr" )
require_ex( "luacommon/object/player_mng" )
require_ex( "luacommon/object/states" )
require_ex( "luacommon/object/obj_t" )
require_ex( "luacommon/object/ctrl_t" )
require_ex( "luacommon/object/drop_item_t")
require_ex( "luacommon/skill/skill_info" )
require_ex( "luacommon/object/spirit_t_module" )
require_ex( "luacommon/object/spirit_t_buff" )
require_ex( "luacommon/object/spirit_t_pasv" )
require_ex( "luacommon/object/spirit_t_fight" )
require_ex( "luacommon/object/spirit_t_color" )
require_ex( "luacommon/object/spirit_t" )
require_ex( "luacommon/object/player_t_module" )
require_ex( "luacommon/object/player_t_net" )
require_ex( "luacommon/object/player_t_fight" )
require_ex( "luacommon/object/player_t_copy" )
require_ex( "luacommon/object/player_t_skill" )
require_ex( "luacommon/object/player_t_element" )
require_ex( "luacommon/object/player_t_item" )
require_ex( "luacommon/object/player_t_rune" )
require_ex( "luacommon/object/player_t_quest")
require_ex( "luacommon/object/player_t_avatar" )
require_ex( "luacommon/object/player_t_soul" )
require_ex( "luacommon/object/player_t_mastery" )
require_ex( "luacommon/object/player_t_mail" )
require_ex( "luacommon/object/player_t_goblin_market")
require_ex( "luacommon/object/player_t_gs")
require_ex( "luacommon/object/player_t_pray")
require_ex( "luacommon/object/player_t_energy")
require_ex( "luacommon/object/player_t_time" )
require_ex( "luacommon/object/player_t_param" )
require_ex( "luacommon/object/player_t_recharge" )
require_ex( "luacommon/object/player_t_newbie_guide")
require_ex( "luacommon/object/player_t_system_data")
require_ex( "luacommon/object/player_t_daily_goals" )
require_ex( "luacommon/object/player_t_mystic" )
require_ex( "luacommon/object/player_t_tower" )
require_ex( "luacommon/object/player_t_palace" )
require_ex( "luacommon/object/player_t_shop" )
require_ex( "luacommon/object/player_t_gold_exchange" )
require_ex( "luacommon/object/player_t_reward" )
require_ex( "luacommon/object/player_t_p2p_trade" )
require_ex( "luacommon/object/player_t_attend" )
require_ex( "luacommon/object/player_t_rmb" )
require_ex( "luacommon/object/player_t_holiday_event" )
require_ex( "luacommon/object/player_t_daily_reset" )
require_ex( "luacommon/object/player_t_system_reset" )
require_ex( "luacommon/object/player_t_snapshot")
require_ex( "luacommon/object/player_t_ladder")
require_ex( "luacommon/object/player_t_chapter")
require_ex( "luacommon/object/player_t_title")
require_ex( "luacommon/object/player_t_team" )
require_ex( "luacommon/object/player_t_guild" )
require_ex( "luacommon/object/player_t_friend")
require_ex( "luacommon/object/player_t_weekly_task" )
require_ex( "luacommon/object/player_t_chat" )
require_ex( "luacommon/object/player_t_inst" )
require_ex( "luacommon/object/player_t_truncheon" )
require_ex( "luacommon/object/player_t_guild_profession" )
require_ex( "luacommon/object/player_t_guild_scene" )
require_ex( "luacommon/object/player_t_guild_donation" )
require_ex( "luacommon/object/player_t_equip_exchange_shop" )
require_ex( "luacommon/object/player_t_permanent_attr" )
require_ex( "luacommon/object/player_t_welfare" )
require_ex( "luacommon/object/player_t_trade" )
require_ex( "luacommon/object/player_t_vip" )
require_ex( "luacommon/object/player_t_auction" )
require_ex( "luacommon/object/player_t_guild_shop" )
require_ex( "luacommon/object/player_t_guild_pve" )
require_ex( "luacommon/object/player_t_prevent_kill_cheat" )
require_ex( "luacommon/object/player_t_customer_service" )
require_ex( "luacommon/object/player_t_guild_boutique" )
require_ex( "luacommon/object/player_t_god_divination" )
require_ex( "luacommon/object/player_t_red" )
require_ex( "luacommon/object/player_t_share" )
require_ex( "luacommon/object/player_t_level_reward" )
require_ex( "luacommon/object/player_t_pet" )
require_ex( "luacommon/object/player_t_celebration" )
require_ex( "luacommon/object/player_t_holiday_signin_award" )
require_ex( "luacommon/object/player_t_monthly_signin_award" )
require_ex( "luacommon/object/player_t_mall" )
require_ex( "luacommon/object/player_t_daily_online_award" )
require_ex( "luacommon/object/player_t_cycled_recharge_award" )
require_ex( "luacommon/object/player_t_growth_fund" )
require_ex( "luacommon/object/player_t_login_activity" )
require_ex( "luacommon/object/player_t_sanding" )
require_ex( "luacommon/object/player_t_survey" )
require_ex( "luacommon/object/player_t_small_data" )
require_ex( "luacommon/object/player_t_battle_justice" )
require_ex( "luacommon/object/player_t_hall" )
require_ex( "luacommon/object/player_t_level_recharge" )
require_ex( "luacommon/object/player_t_like" )
require_ex( "luacommon/object/player_t_carnival" )
require_ex( "luacommon/object/player_t_one_gold_lucky_draw" )
require_ex( "luacommon/object/player_t_egg" )
require_ex( "luacommon/object/player_t_festival" )
require_ex( "luacommon/object/player_t_player_chat_gift" )
require_ex( "luacommon/object/player_t_christmas_sell" )
require_ex( "luacommon/object/player_t_christmas_recharge_lucky_draw" )
require_ex( "luacommon/object/player_t_wing_system" )
require_ex( "luacommon/object/player_t_stage_star" )
require_ex( "luacommon/object/player_t_soulcard" )
--$PLAYER_MODULE
require_ex( "luacommon/object/player_t_guild_weekend" )
require_ex( "luacommon/object/player_t_runner" )
require_ex( "luacommon/object/player_t_assist_box" )
require_ex( "luacommon/object/player_t_wild" )
require_ex( "luacommon/object/player_t_guild_merchant_task" )
require_ex( "luacommon/object/player_t_guildprof_task" )
require_ex( "luacommon/object/player_t_recruit" )
require_ex( "luacommon/object/player_t_team_ladder" )
require_ex( "luacommon/object/player_t_parchment" )
require_ex( "luacommon/object/player_t" )
require_ex( "luacommon/object/monster_t_module" )
require_ex( "luacommon/object/monster_t_robot" )
require_ex( "luacommon/object/monster_t_dead_effects" )
require_ex( "luacommon/object/monster_t_effects" )
require_ex( "luacommon/object/monster_t_fight" )
require_ex( "luacommon/object/monster_t_share_hp" )
require_ex( "luacommon/object/monster_t" )
require_ex( "luacommon/object/player_t_arena" )
require_ex( "luacommon/event/event_honor_hall/random_name_lib" )

require_ex( "luacommon/trade/pray_system" )

require_ex( "luacommon/trigger_impl/trigger_extend/trigger_const_params" )
require_ex( "luacommon/module/trigger_timer" )
require_ex( "luacommon/trigger_impl/trigger_action_t" )
require_ex( "luacommon/trigger_impl/trigger_impl_t" )
require_ex( "luacommon/trigger_impl/aoi_action_impl_t" )
require_ex( "luacommon/trigger_impl/aoi_impl_t" )
require_ex( "luacommon/trigger_impl/battle_station")
require_ex( "luacommon/trigger_impl/counter_impl_t" )
require_ex( "luacommon/trigger_impl/kill_counter_impl_t" )
require_ex( "luacommon/trigger_impl/sfx_player_impl_t" )
require_ex( "luacommon/trigger_impl/skill_user_impl_t" )
require_ex( "luacommon/trigger_impl/cinema_impl_t" )
require_ex( "luacommon/trigger_impl/summon_impl_t" )
require_ex( "luacommon/trigger_impl/func_impl_t" )
require_ex( "luacommon/trigger_impl/rater_impl_t" )
require_ex( "luacommon/trigger_impl/ctrl_npc_impl_t" )
require_ex( "luacommon/trigger_impl/onhit_impl_t" )
require_ex( "luacommon/trigger_impl/slot_machine_impl_t" )
require_ex( "luacommon/trigger_impl/task_impl_t")
require_ex( "luacommon/trigger_impl/wandering_singer_impl_t" )
require_ex( "luacommon/trigger_impl/progress_impl_t" )
require_ex( "luacommon/trigger_impl/aoi_toggle_impl_t" )
require_ex( "luacommon/trigger_impl/trigger_extend/trigger_jixiemicheng_random" )
require_ex( "luacommon/trigger_impl/trigger_func" )
require_ex( "luacommon/trigger_impl/pass_counter_impl_t")
require_ex( "luacommon/trigger_impl/inscription_impl_t")
require_ex( "luacommon/trigger_impl/trap_impl_t" )
require_ex( "luacommon/trigger_impl/stay_statics_impl_t" )
require_ex( "luacommon/object/trigger_t" )

require_ex( "luacommon/ai/ai_t_util" )
require_ex( "luacommon/ai/ai_t" )
require_ex( "luacommon/ai/ai_t_actions" )
require_ex( "luacommon/ai/ai_t_action_func" )
require_ex( "luacommon/ai/ai_t_cond_func" )
require_ex( "luacommon/object/bullet_t" )
require_ex( "luacommon/object/missile_t" )
require_ex( "luacommon/object/ctrl_mng" )

require_ex( "luacommon/object/event_mng" )

CITY_SPAWN_POS_CONFIG = require_ex("luacommon/setting/CITY_SPAWN_POS_CONFIG")
require_ex( "luacommon/city/channel_mng" )
CITY_SPAWN_DATA = require_ex("luacommon/setting/spawn/editSPAWN_DATA_" .. channel_mng.CITY_SCENE_ID)
WORLD_CONFIG = require_ex("luacommon/setting/resource/world_config")

require_ex( "luacommon/object/summon_mng" )
require_ex( "luacommon/object/magic_area_mng" )
require_ex( "luacommon/object/magic_area_t" )

require_ex( "luacommon/skill/effect_func_skill" ) 
require_ex( "luacommon/skill/effect_func_cond" )
require_ex( "luacommon/skill/effect_func_buff" ) 
require_ex( "luacommon/skill/effect_func_pasv" )
require_ex( "luacommon/skill/blood_attack_mng" )
require_ex( "luacommon/skill/skill_effect_runner" ) 
require_ex( "luacommon/skill/fight_stat" )
require_ex( "luacommon/skill/step_attack_mng" )

require_ex( "luacommon/coupon/coupon_mng" )


--no or, force to reload skill table
BULLETS = require_ex("luacommon/setting/BULLETS") 
MISSILES = require_ex("luacommon/setting/MISSILES") 
SKILLS = require_ex("luacommon/setting/SKILLS") 
PASV_SKILLS = require_ex("luacommon/setting/PASV_SKILLS") 
SKILL_FACTOR = require_ex("luacommon/setting/SKILL_FACTOR") 
FIGHT_STATS = require_ex("luacommon/setting/FIGHT_STATS") 
MAGIC_AREA = require_ex("luacommon/setting/MAGIC_AREA") 
SCULPTS = require_ex("luacommon/setting/SCULPTS") 
MODELS = require_ex("luacommon/setting/MODELS") 
BUFFS = require_ex("luacommon/setting/BUFFS") 
TRIGGER_ACTION = require_ex( "luacommon/setting/TRIGGER_ACTION" )
TRIGGER_DATA = require_ex( "luacommon/setting/TRIGGER_DATA" )
CHAR_AI = require_ex("luacommon/setting/ai/CHAR_AI")
REVIVE_CONFIG = require_ex("luacommon/setting/REVIVE_CONFIG")

ELEMENT_MASTER_SKILLS = require_ex("luacommon/setting/ELEMENT_MASTER_SKILLS")
ELEMENT_PRACTICE_SKILLS = require_ex("luacommon/setting/ELEMENT_PRACTICE_SKILLS")
ELEMENT_MASTER_SKILL_PARAMS = require_ex("luacommon/setting/ELEMENT_MASTER_SKILL_PARAMS")
ELEMENT_PRACTICE_SKILL_PARAMS = require_ex("luacommon/setting/ELEMENT_PRACTICE_SKILL_PARAMS")
SKILL_CORRECTION = require_ex("luacommon/setting/SKILL_CORRECTION")
SKILL_DAMAGE = require_ex("luacommon/setting/SKILL_DAMAGE")

MODEL_INFO = require_ex("luacommon/setting/MODEL_INFO") 
ROBOTS = require_ex("luacommon/setting/ROBOTS") 
MONSTER_DATA = require_ex("luacommon/setting/MONSTER_DATA") 
MONSTER_ATTR_ADJ = require_ex("luacommon/setting/MONSTER_ATTR_ADJ") 
MONSTER_LEVEL_ATTR = require_ex("luacommon/setting/MONSTER_LEVEL_ATTR")
MONSTER_ATTR_TEMPLATE = require_ex("luacommon/setting/MONSTER_ATTR_TEMPLATE")
MONSTER_ATTR_TEMPLATE2 = require_ex("luacommon/setting/MONSTER_ATTR_TEMPLATE2")

SUMMON_FORMATIONS = require_ex("luacommon/setting/SUMMON_FORMATIONS")
CAMPS = require_ex("luacommon/setting/CAMPS") 
BEZIER_CURVES = require_ex("luacommon/setting/BEZIER_CURVES") 
WAVE_PATHS = require_ex("luacommon/setting/WAVE_PATHS") 
EXP = require_ex("luacommon/setting/EXP") 
EQUIP_GS = require_ex("luacommon/setting/EQUIP_GS")
ITEMS = require_ex("luacommon/setting/ITEMS")
REBORN_RATES = require_ex("luacommon/setting/REBORN_RATES")
REBORN_ADDITIONAL_RATE = require_ex( "luacommon/setting/REBORN_ADDITIONAL_RATE" )
EQUIPS = require_ex("luacommon/setting/EQUIPS")
EQUIP_NON_ATTR_BUFFS = require_ex("luacommon/setting/EQUIP_NON_ATTR_BUFFS")
USELEVEL_DECREASED_EQUIPS = require_ex("luacommon/setting/USELEVEL_DECREASED_EQUIPS")
EQUIP_ATTRS = require_ex("luacommon/setting/EQUIP_ATTRS")
EQUIP_DECOMPOSE = require_ex("luacommon/setting/EQUIPS_DECOMPOSE")
PATH = require_ex("luacommon/setting/PATH")
PLANE_STAR = require_ex("luacommon/setting/PLANE_STAR")
DROP_EQUIPS = require_ex("luacommon/setting/DROP_EQUIPS")
DROP_CURRENCY = require_ex("luacommon/setting/DROP_CURRENCY")
DROP_ITEMS = require_ex("luacommon/setting/DROP_ITEMS")
DROP_FIRST_TIME_MUST_DROP =  require_ex("luacommon/setting/DROP_FIRST_TIME_MUST_DROP")
DROP_ID_CHANGE_CONFIG = require_ex("luacommon/setting/DROP_ID_CHANGE_CONFIG")
DROP_LEVEL_CHANGE_CONFIG = require_ex("luacommon/setting/DROP_LEVEL_CHANGE_CONFIG")
ITEM_RUNES = require_ex("luacommon/setting/ITEM_RUNES")
ITEM_RUNES_GOLD = require_ex("luacommon/setting/ITEM_RUNES_GOLD")
RUNE_GROUP_RATE = require_ex("luacommon/setting/RUNE_GROUP_RATE")
ITEM_REFINE = require_ex("luacommon/setting/ITEM_REFINE")
ITEM_AFFIX = require_ex("luacommon/setting/ITEM_AFFIX")
ITEM_REFINE_FACTOR = require_ex("luacommon/setting/ITEM_REFINE_FACTOR")
ITEM_STONE = require_ex("luacommon/setting/ITEM_STONE")
ITEM_STONE_LEVELUP = require_ex("luacommon/setting/ITEM_STONE_LEVELUP")
ITEM_MAGIC = require_ex("luacommon/setting/ITEM_MAGIC")
ITEM_MAGIC_ATTRS = require_ex("luacommon/setting/ITEM_MAGIC_ATTRS")
EQUIP_AWAKE1 = require_ex("luacommon/setting/EQUIP_AWAKE1")
EQUIP_AWAKE2 = require_ex("luacommon/setting/EQUIP_AWAKE2")
EQUIP_AWAKE3 = require_ex("luacommon/setting/EQUIP_AWAKE3")
EQUIP_AWAKE4 = require_ex("luacommon/setting/EQUIP_AWAKE4")
EQUIP_AWAKE5 = require_ex("luacommon/setting/EQUIP_AWAKE5")
EQUIP_AWAKE_SINGLE_EFFECT = require_ex("luacommon/setting/EQUIP_AWAKE_SINGLE_EFFECT")
EQUIP_AWAKE_SUIT_EFFECT = require_ex("luacommon/setting/EQUIP_AWAKE_SUIT_EFFECT")
EQUIP_AWAKE_SFXS = require_ex("luacommon/setting/EQUIP_AWAKE_SFXS")
PLANE_DROP = require_ex("luacommon/setting/PLANE_DROP")
PLAYER_RUNES = require_ex("luacommon/setting/PLAYER_RUNES")
PLAYER_RUNE_RANK = require_ex("luacommon/setting/PLAYER_RUNE_RANK")
QUEST_1_HEIANZHIMEN = require_ex( "luacommon/setting/QUEST_1_HEIANZHIMEN")
HEIANZHIMEN_CARD_CONFIG = require_ex( "luacommon/setting/HEIANZHIMEN_CARD_CONFIG")
QUEST_2_MAMMONS_TREASURE = require_ex( "luacommon/setting/QUEST_2_MAMMONS_TREASURE")
HIGHEST_SURVIVAL_CONFIG = require_ex("luacommon/setting/HIGHEST_SURVIVAL_CONFIG")
QUESTS = require_ex( "luacommon/setting/QUESTS")
TARGETS = require_ex( "luacommon/setting/TARGETS")
WEEKLY_TASKS = require_ex( "luacommon/setting/WEEKLY_TASKS" )
WEEKLY_TARGETS = require_ex( "luacommon/setting/WEEKLY_TARGETS" )
WEEKLY_TASK_PRIZE_CONFIG = require_ex( "luacommon/setting/WEEKLY_TASK_PRIZE_CONFIG" )
WEEKLY_TASK_SYS_CONFIG = require_ex( "luacommon/setting/WEEKLY_TASK_SYS_CONFIG" )

SOULCARD_ATTRS = require_ex( "luacommon/setting/SOULCARD_ATTRS" )
SOULCARD_DECOMPOSE = require_ex( "luacommon/setting/SOULCARD_DECOMPOSE" )
SOULCARD_REFINE = require_ex( "luacommon/setting/SOULCARD_REFINE" )
SOULCARD_REFINE_CONSUME = require_ex( "luacommon/setting/SOULCARD_REFINE_CONSUME" )
SOULCARD_REFINE_RATE = require_ex( "luacommon/setting/SOULCARD_REFINE_RATE" )
SOULCARD_REFINE_UNLOCK = require_ex( "luacommon/setting/SOULCARD_REFINE_UNLOCK" )
SOULCARD_SLOT_UNLOCK = require_ex( "luacommon/setting/SOULCARD_SLOT_UNLOCK" )
SOULCARD_STAR = require_ex( "luacommon/setting/SOULCARD_STAR" )
SOULCARDS = require_ex( "luacommon/setting/SOULCARDS" )

MILLIONAIRE_CELL_MAP = require_ex( "luacommon/setting/MILLIONAIRE_CELL_MAP" )
MILLIONAIRE_ROUTE_MAP = require_ex( "luacommon/setting/MILLIONAIRE_ROUTE_MAP" )
MILLIONAIRE_DATA_CONFIG = require_ex( "luacommon/setting/MILLIONAIRE_DATA_CONFIG" )

RANDOM_ITEM_LIBS = require_ex( "luacommon/setting/RANDOM_ITEM_LIBS" )
MAILS = require_ex( "luacommon/setting/MAILS" )
TIME_CTRL = require_ex( "luacommon/setting/TIME_CTRL" )
TAMRIEL_RELIC = require_ex( "luacommon/setting/TAMRIEL_RELIC" )
FIVE_PVP_CONFIG = require_ex( "luacommon/setting/FIVE_PVP_CONFIG" )
MESSAGES = require_ex( "luacommon/setting/MESSAGES" )
HOLIDAYS = require_ex( "luacommon/setting/HOLIDAYS")
LEVEL_CONST = require_ex( "luacommon/setting/LEVEL_CONST" )
BULLETIN = require_ex( "luacommon/setting/BULLETIN")
TOWER_CONFIG = require_ex( "luacommon/setting/TOWER_CONFIG")
MINOTAUR_BUFF = require_ex( "luacommon/setting/MINOTAUR_BUFF")
MINOTAUR = require_ex( "luacommon/setting/MINOTAUR")
HONOR_HALL = require_ex( "luacommon/setting/HONOR_HALL")
HONOR_LADDER_AWARD_CONFIG = require_ex( "luacommon/setting/HONOR_LADDER_AWARD_CONFIG")
HONOR_TOUR_AWARD_CONFIG = require_ex( "luacommon/setting/HONOR_TOUR_AWARD_CONFIG")
BRIEF_TIPS_CFG = require_ex( "luacommon/setting/BRIEF_TIPS_CONFIG")
SYSTEM_UNLOCK = require_ex( "luacommon/setting/SYSTEM_UNLOCK" )
ATTEND_CFG = require_ex( "luacommon/setting/ATTEND_CONFIG" )
GACHA_CFG = require_ex( "luacommon/setting/GACHA_CONFIG" )
LEVEL_REWARD_CONFIG = require_ex( "luacommon/setting/LEVEL_REWARD_CONFIG" )
DISPLAY_NAME_CONFIG = require_ex( "luacommon/setting/DISPLAY_NAME_CONFIG" )
LEVEL_ATTEND_REWARD_CONFIG = require_ex("luacommon/setting/LEVEL_ATTEND_REWARD_CONFIG")
NPC_SUITS = require_ex("luacommon/setting/NPC_SUITS")
QUESTION_CONFIG = require_ex("luacommon/setting/QUESTION_CONFIG")
QUESTION_LIB_CONFIG = require_ex("luacommon/setting/QUESTION_LIB_CONFIG")
PRICE_BOARD_CONTENT_CONFIG = require_ex("luacommon/setting/PRICE_BOARD_CONTENT_CONFIG")
PRICE_BOARD_CONFIG = require_ex("luacommon/setting/PRICE_BOARD_CONFIG")
TIME_LIMITED_ENTRANCE_CONFIG = require_ex("luacommon/setting/TIME_LIMITED_ENTRANCE_CONFIG")
WEEKEND_PVP_CONFIG = require_ex( "luacommon/setting/WEEKEND_PVP_CONFIG" )
EVENT_TEAM_LADDER_CONFIG = require_ex( "luacommon/setting/EVENT_TEAM_LADDER_CONFIG" )
EVENT_TEAM_CHAMPION_CONFIG = require_ex( "luacommon/setting/EVENT_TEAM_CHAMPION_CONFIG" )
CHAT_CONFIG = require_ex( "luacommon/setting/CHAT_CONFIG" )
EQUIP_EXCHANGE_SHOP_CONFIG = require_ex( "luacommon/setting/EQUIP_EXCHANGE_SHOP_CONFIG" )
PERMANENT_ATTR_ITEM_CONFIG = require_ex( "luacommon/setting/PERMANENT_ATTR_ITEM_CONFIG" ) 
EVENT_ARES_CONFIG = require_ex( "luacommon/setting/EVENT_ARES_CONFIG" )
GUILD_DAILY_PVP_CONFIG = require_ex( "luacommon/setting/GUILD_DAILY_PVP_CONFIG" )
MINI_RECHARGE_AWARD_CONFIG = require_ex( "luacommon/setting/MINI_RECHARGE_AWARD_CONFIG" )

PUSH_MESSAGES = require_ex( "luacommon/setting/PUSH_MESSAGES" )

PICK_POINTS = require_ex("luacommon/setting/PICK_POINTS") 
TRAPS = require_ex("luacommon/setting/TRAPS") 
ASSIST_BOX_CONFIG = require_ex("luacommon/setting/ASSIST_BOX_CONFIG") 

SHARE_REWARD_ITEM_LIB = require_ex("luacommon/setting/SHARE_REWARD_ITEM_LIB")
SHARE_REWARD_CONFIG = require_ex("luacommon/setting/SHARE_REWARD_CONFIG")

TREASURE_HUNT_CONFIG = require_ex("luacommon/setting/TREASURE_HUNT_CONFIG")
TREASURE_HUNT_EVENT_CONFIG = require_ex("luacommon/setting/TREASURE_HUNT_EVENT_CONFIG")
TREASURE_HUNT_AWARD_CONFIG = require_ex("luacommon/setting/TREASURE_HUNT_AWARD_CONFIG")
BOSS_DROP_CONFIG = require_ex("luacommon/setting/BOSS_DROP_CONFIG")
COLOSSUS_REWARD_CONFIG = require_ex("luacommon/setting/COLOSSUS_REWARD_CONFIG")

STAGE_GET_STAR_CONFIG = require_ex("luacommon/setting/STAGE_GET_STAR_CONFIG")
STAGE_STAR_REWARD_CONFIG = require_ex("luacommon/setting/STAGE_STAR_REWARD_CONFIG")

AVATAR_RELIC_DRAW_CONFIG = require_ex("luacommon/setting/AVATAR_RELIC_DRAW_CONFIG")
AVATAR_RELIC_DRAW_PRIZE_POOL = require_ex("luacommon/setting/AVATAR_RELIC_DRAW_PRIZE_POOL")
AVATAR_RELIC_DRAW_PRIZE = require_ex("luacommon/setting/AVATAR_RELIC_DRAW_PRIZE")

AVATAR_CHIP_DRAW_CONFIG = require_ex("luacommon/setting/AVATAR_CHIP_DRAW_CONFIG")

PET_DRAW_CONFIG = require_ex("luacommon/setting/PET_DRAW_CONFIG")
PET_DRAW_PRIZE_POOL = require_ex("luacommon/setting/PET_DRAW_PRIZE_POOL")
PET_DRAW_PRIZE = require_ex("luacommon/setting/PET_DRAW_PRIZE")
REBORN_RESULT_RATE_REVISE = require_ex("luacommon/setting/REBORN_RESULT_RATE_REVISE")
ONE_STAGE_STAR_REWARD_CONFIG = require_ex("luacommon/setting/ONE_STAGE_STAR_REWARD_CONFIG")
BLESSING_OF_FREYA_CONFIG = require_ex("luacommon/setting/BLESSING_OF_FREYA_CONFIG")

require_ex( "luacommon/formula/monster_attr" )
require_ex( "luacommon/trade/mystic_dealer" )
require_ex( "luacommon/time_event/time_event_carnival" )
require_ex( "luacommon/time_event/time_event_system_reset" )
require_ex( "luacommon/time_event/time_event_utils" )
require_ex( "luacommon/time_event/time_event" )
require_ex( "luacommon/time_event/event_calendar" )
require_ex( "luacommon/time_ctrl/time_ctrl" )
require_ex( "luacommon/timer/timers" )
require_ex( "timer/timers" )
require_ex( "luacommon/chat/chat_msg_t" )
require_ex( "luacommon/chat/chat_mng" )
require_ex( "luacommon/chat/chat_net" )
require_ex( "luacommon/net/gamesvr_set_value" )
require_ex( "luacommon/net/gamesvr_item" )
require_ex( "luacommon/net/gamesvr_safe" )
require_ex( "luacommon/net/gamesvr" )
require_ex( "luacommon/client_logic_mask" )

HIDE_INSTANCE_RATE = require_ex("luacommon/setting/HIDE_INSTANCE_RATE") 
require_ex( "luacommon/plane/planemng" )
require_ex( "luacommon/plane/plane_t" )
require_ex( "luacommon/instance/separate_frame_handler")
require_ex( "luacommon/instance/data_handle")
require_ex( "luacommon/instance/instance_t_const")
require_ex( "luacommon/instance/instance_join_check")
require_ex( "luacommon/instance/instance_mng_misc")
require_ex( "luacommon/instance/instance_mng")
require_ex( "luacommon/instance/instance_t")
require_ex( "luacommon/instance/instance_t_extend")
require_ex( "luacommon/instance/instance_t_reward")
require_ex( "luacommon/instance/instance_t_drop")
require_ex( "luacommon/instance/instance_t_spawn")
require_ex( "luacommon/instance/instance_star_mgr")
require_ex( "luacommon/instance/instance_sweep")
require_ex( "luacommon/instance/instance_exp_t")
require_ex( "luacommon/instance/instance_honor_t")
require_ex( "luacommon/instance/instance_glory_t" )
require_ex( "luacommon/instance/instance_t_drop_data_loader")
require_ex( "luacommon/instance/instance_t_millionaire")
require_ex( "luacommon/instance/instance_t_guild_pve")
require_ex( "luacommon/instance/instance_t_door")
require_ex( "luacommon/instance/instance_t_minimap")
require_ex( "luacommon/instance/instance_t_justice")

require_ex( "luacommon/item/item_t_use" )
require_ex( "luacommon/item/item_t_rouleau")
require_ex( "luacommon/item/item_t_buff" )
require_ex( "luacommon/item/item_t_reborn" )
require_ex( "luacommon/item/item_t_awake" )
require_ex( "luacommon/item/item_t_rune")
require_ex( "luacommon/item/item_t_stone")
require_ex( "luacommon/item/item_t_inherit")
require_ex( "luacommon/item/item_t_refine" )
require_ex( "luacommon/item/item_t_magic" )
require_ex( "luacommon/item/item_t_decompose" )
require_ex( "luacommon/item/item_t_skillbook" )
require_ex( "luacommon/item/item_t_orange" )
require_ex( "luacommon/item/item_t_equip_gs" )
require_ex( "luacommon/item/item_t_equip" )
require_ex( "luacommon/item/item_t_warehouse" )
require_ex( "luacommon/item/item_t_const" )
require_ex( "luacommon/item/item_t_soulcard" )
require_ex( "luacommon/item/item_t" )
require_ex( "luacommon/item/bag_t_warehouse" )
require_ex( "luacommon/item/bag_t" )

require_ex( "luacommon/mail/mail_t" )
require_ex( "luacommon/mail/mail_box_t" )

require_ex( "luacommon/event/event_common_func")
require_ex( "luacommon/event/event_tamriel_relic/tamriel_relic_robot" )
require_ex( "luacommon/event/event_tamriel_relic/tamriel_relic_game" )
require_ex( "luacommon/event/event_tamriel_relic/tamriel_relic" )
require_ex( "luacommon/event/event_five_pvp/five_pvp_common" )
require_ex( "luacommon/event/event_five_pvp/five_pvp_match_gs" )
require_ex( "luacommon/event/event_five_pvp/five_pvp" )
require_ex( "luacommon/event/event_ares/ares_witness_match" )
require_ex( "luacommon/event/event_ares/ares_witness_game" )
require_ex( "luacommon/event/event_honor_hall/honor_witness_match" )
require_ex( "luacommon/event/event_honor_hall/honor_witness_game" )
require_ex( "luacommon/event/event_ares/event_ares_game" )
require_ex( "luacommon/event/event_honor_hall/bucket_rank_t" )
require_ex( "luacommon/event/event_honor_hall/honor_hall_match" )
require_ex( "luacommon/event/event_honor_hall/honor_hall_rank" )
require_ex( "luacommon/event/event_honor_hall/honor_hall_score_award" )
require_ex( "luacommon/event/event_honor_hall/honor_hall" )
require_ex( "luacommon/event/event_honor_hall/honor_ladder_game" )
require_ex( "luacommon/event/event_honor_hall/honor_ladder_center" )
require_ex( "luacommon/event/event_honor_hall/honor_ladder_bf" )
require_ex( "luacommon/event/event_honor_hall/honor_tour_game" )
require_ex( "luacommon/event/event_weekend_pvp/event_weekend_pvp_match" )
require_ex( "luacommon/event/event_weekend_pvp/event_weekend_pvp_battle" )
require_ex( "luacommon/event/event_question/event_question" )
require_ex( "luacommon/event/event_price_board/event_price_board" )
require_ex( "luacommon/event/time_limited_entrance" )
require_ex( "luacommon/event/pvp_main_ui_entrance" )
require_ex( "luacommon/event/event_millionaire/millionaire_pvp")
require_ex( "luacommon/event/event_millionaire/millionaire_pvp_match")
require_ex( "luacommon/event/event_millionaire/millionaire_pvp_event")
require_ex( "luacommon/event/event_guild_daily_pvp/guild_daily_pvp_match")
require_ex( "luacommon/event/event_guild_daily_pvp/guild_daily_pvp_battle")
require_ex( "luacommon/event/event_guild_daily_pvp/guild_daily_pvp_rank_info_t")
require_ex( "luacommon/event/event_guild_campfire_party/event_guild_campfire_party")
require_ex( "luacommon/event/event_one_gold_lucky_draw/event_one_gold_lucky_draw")
require_ex( "luacommon/event/event_god_divination/event_god_divination")
require_ex( "luacommon/event/event_team_ladder/event_team_ladder_utils" )
require_ex( "luacommon/event/event_team_ladder/event_team_ladder_game" )
require_ex( "luacommon/event/event_team_ladder/event_team_ladder_rank_t" )
require_ex( "luacommon/event/event_team_ladder/ladder_team_t" )
require_ex( "luacommon/event/event_team_champion/event_team_champion_utils" )
require_ex( "luacommon/event/event_team_champion/event_team_champion_game" )

require_ex( "luacommon/event/event_arena/arena_battle" )
require_ex( "luacommon/event/event_arena/arena_battle_game" )
require_ex( "luacommon/event/event_experience_circle/fight_experience_circle" )

require_ex( "luacommon/drop/drop_t_packet")
require_ex( "luacommon/drop/monster_t_drop")
require_ex( "luacommon/drop/drop_currency")
require_ex( "luacommon/drop/random_item_libs")
require_ex( "luacommon/drop/drop_addition_t")
require_ex( "luacommon/drop/drop_tower_mng")
require_ex( "luacommon/drop/lucky_rate")

require_ex( "luacommon/quest/quest_target_t")
require_ex( "luacommon/quest/quest_main_t")
require_ex( "luacommon/quest/quest_heianzhimen_t")
require_ex( "luacommon/quest/quest_mammons_treasure")
require_ex( "luacommon/quest/quest_highest_survival_t")
require_ex( "luacommon/quest/quest_worldmap_t")
require_ex( "luacommon/quest/quest_t")
require_ex( "luacommon/quest/quest_millionaire_mng" )

require_ex( "luacommon/npc_interaction/npc_interaction_mng" )
require_ex( "luacommon/daily_goals/daily_goals_mgr" )
require_ex( "luacommon/runner/runner_mng" )

require_ex( "luacommon/module/system_unlock_mgr" )

require_ex( "luacommon/module/client_access_switch" )

require_ex( "luacommon/task/task_misc" )

require_ex( "gm_cmd" )
require_ex( "luacommon/gm_cmd" )
require_ex( "login/login_base" )
require_ex( "login/login_mng" )

--排行榜
RANK_TYPE = require_ex( "luacommon/setting/RANK_TYPE" )
require_ex( "luacommon/rank_list/heap_t" )
require_ex( "luacommon/rank_list/rank_info_t" )
require_ex( "luacommon/rank_list/team_rank_info_t" )
require_ex( "luacommon/rank_list/team_champion_rank_info_t" )
require_ex( "luacommon/rank_list/guild_rank_info_t" )
require_ex( "luacommon/rank_list/resource_magnate_rank_info_t" )
require_ex( "luacommon/rank_list/rank_common" )
require_ex( "luacommon/rank_list/rank_list_mng" )
require_ex( "luacommon/rank_list/rank_net" )

-- 好友
require_ex( "luacommon/friend/friend_const" )
require_ex( "luacommon/friend/friend_mng" )
require_ex( "luacommon/friend/friend_mng_core" )
require_ex( "luacommon/friend/friend_mng_center" )
require_ex( "luacommon/friend/friend_t" )
require_ex( "luacommon/friend/friend_set_t" )
require_ex( "luacommon/friend/friend_history_t" )
require_ex( "luacommon/friend/friend_history_list_t" )

--公会
require_ex( "net/game_zone_mng" )
require_ex( "luacommon/guild/guild_mng" )
require_ex( "luacommon/guild/guild_mng_workflow_db" )
require_ex( "luacommon/guild/guild_mng_workflow_add_popu" )
require_ex( "luacommon/guild/guild_mng_workflow_apply" )
require_ex( "luacommon/guild/guild_mng_workflow_change_desc" )
require_ex( "luacommon/guild/guild_mng_workflow_create" )
require_ex( "luacommon/guild/guild_mng_workflow_invite" )
require_ex( "luacommon/guild/guild_mng_workflow_kick" )
require_ex( "luacommon/guild/guild_mng_workflow_login" )
require_ex( "luacommon/guild/guild_mng_workflow_quit" )
require_ex( "luacommon/guild/guild_mng_workflow_refresh" )
require_ex( "luacommon/guild/guild_mng_workflow_search" )
require_ex( "luacommon/guild/guild_mng_workflow_set_role" )
require_ex( "luacommon/guild/guild_mng_workflow_apply_goods" )
require_ex( "luacommon/guild/guild_mng_workflow_add_guild_attr" )
require_ex( "luacommon/guild/guild_mng_workflow_lock" )
require_ex( "luacommon/guild/guild_mng_workflow_donate" )
require_ex( "luacommon/guild/guild_mng_workflow_change_value" )
require_ex( "luacommon/guild/guild_mng_workflow_rename" )
require_ex( "luacommon/guild/guild_mng_workflow_add_officer_box" )
require_ex( "luacommon/guild/guild_mng_profession" )
require_ex( "luacommon/guild/guild_mng_donation" )
require_ex( "luacommon/guild/guild_mng_utils" )
require_ex( "luacommon/guild/guild_mng_hash_array" )
require_ex( "luacommon/guild/guild_cache" )
require_ex( "luacommon/guild/guild_scene_mng" )
require_ex( "luacommon/module/player_gs_offline_op_mng" )
require_ex( "luacommon/guild/guild_mng_pve" )
require_ex( "luacommon/guild/guild_mng_pve_act" )
require_ex( "luacommon/guild/guild_mng_workflow_pve" )
require_ex( "luacommon/guild/boutique_item_t" )
require_ex( "luacommon/guild/guild_mng_boutique" )
require_ex( "luacommon/guild/guild_mng_daily_task" )

require_ex( "luacommon/bulletin/bulletin_mng") 
require_ex( "luacommon/object/pick_point_t" )
require_ex( "luacommon/object/pick_point_mng" )

-- team 
require_ex( "luacommon/team/team_t") 
require_ex( "luacommon/team/team_net") 
require_ex( "luacommon/team/team_mng_gs") 
require_ex( "luacommon/team/team_net") 
require_ex( "luacommon/team/team_match_gs") 
require_ex( "luacommon/team/team_confirm_gs" )
--require_ex( "luacommon/team/team_test") 

require_ex( "luacommon/team/team_inst_gs") 

-- recruit
require_ex( "luacommon/recruit/recruit_member_t") 
require_ex( "luacommon/recruit/recruit_event") 
require_ex( "luacommon/recruit/recruit_t") 
require_ex( "luacommon/recruit/recruit_mng_gs") 
require_ex( "luacommon/recruit/recruit_msg") 

TRUNCHEON_REFINE = require_ex( "luacommon/setting/TRUNCHEON_REFINE" )
TRUNCHEON_REBORN = require_ex( "luacommon/setting/TRUNCHEON_REBORN" )
TRUNCHEON_REBORN_COST = require_ex( "luacommon/setting/TRUNCHEON_REBORN_COST" )
TRUNCHEON_LETTERING = require_ex( "luacommon/setting/TRUNCHEON_LETTERING" )
TRUNCHEON_LETTERING_GROUP = require_ex( "luacommon/setting/TRUNCHEON_LETTERING_GROUP" )
TRUNCHEON_LETTERING_DICT = require_ex( "luacommon/setting/TRUNCHEON_LETTERING_DICT" )


MONSTER_SPECIAL_SPAWN_CONFIG = require_ex( "luacommon/setting/MONSTER_SPECIAL_SPAWN_CONFIG" )

WELFARE_CONFIG = require_ex( "luacommon/setting/WELFARE_CONFIG" )

BUY_GOLD = require_ex( "luacommon/setting/BUY_GOLD" )


RESOURCE_MAGNATE_RANK_REWARD = require_ex( "luacommon/setting/RESOURCE_MAGNATE_RANK_REWARD" )
RESOURCE_MAGNATE_MALL = require_ex( "luacommon/setting/RESOURCE_MAGNATE_MALL" )
RESOURCE_MAGNATE_STAGE_REWARD = require_ex( "luacommon/setting/RESOURCE_MAGNATE_STAGE_REWARD" )
RESOURCE_MAGNATE_ACCUMULATE_POINT = require_ex( "luacommon/setting/RESOURCE_MAGNATE_ACCUMULATE_POINT" )


ACTIVITY_GROUP_BUY = require_ex( "luacommon/setting/ACTIVITY_GROUP_BUY" )

RESOURCE_FUND = require_ex( "luacommon/setting/RESOURCE_FUND" )


--trade 
require_ex( "luacommon/trade/map_t" )
require_ex( "luacommon/trade/trade_item_t" )
require_ex( "luacommon/trade/gs_trade_mng" )
require_ex( "luacommon/trade/trade_net" )
require_ex( "luacommon/trade/trade_statistic_mng" )
require_ex( "luacommon/trade/trade_statistic_t" )

--auction
require_ex( "luacommon/auction/auction_item_t" )
require_ex( "luacommon/auction/gs_auction_mng" )
require_ex( "luacommon/auction/auction_common" )
require_ex( "luacommon/auction/auction_net" )

-- guild weekend
require_ex( "luacommon/event/event_guild_weekend/guild_weekend_utils" )
require_ex( "luacommon/event/event_guild_weekend/guild_weekend_time_line" )
require_ex( "luacommon/event/event_guild_weekend/guild_weekend_enroll_guild_gs" )
require_ex( "luacommon/event/event_guild_weekend/guild_weekend_enroll_gs" )
require_ex( "luacommon/event/event_guild_weekend/guild_weekend_mng_gs" )

require_ex( "luacommon/treasure_hunt/treasure_hunt_shop" )
require_ex( "luacommon/treasure_hunt/treasure_hunt" )
require_ex( "luacommon/treasure_hunt/treasure_hunt_event" )

require_ex( "luacommon/red/red_mng" )

require_ex( "luacommon/pet/pet_mng" )

require_ex( "luacommon/mall/mall_mng" )
require_ex( "luacommon/mall/mall_time" )

require_ex( "tower/tower_rank_mng" )
require_ex( "luacommon/module/attend_push_mng" )
require_ex( "palace/palace_rank_mng" )

require_ex( "luacommon/arena/arena_mng" )
require_ex( "luacommon/object/player_t_activity" )
require_ex( "luacommon/object/player_t_vip_reward" )
require_ex( "luacommon/object/player_t_resource_magnate" )
require_ex( "luacommon/object/player_t_group_buy" )
require_ex( "luacommon/object/player_t_resource_fund" )
require_ex( "luacommon/activity/activity_mng" )
require_ex( "luacommon/activity/activity_mng_resource_magnate" )
require_ex( "luacommon/activity/activity_mng_group_buy" )
require_ex( "luacommon/activity/activity_mng_avatar_lottery" )
require_ex( "luacommon/activity/activity_mng_resource_fund" )

require_ex( "luacommon/object/player_t_avatar_relic_draw" )
require_ex( "luacommon/object/player_t_pet_draw" )
require_ex( "luacommon/object/player_t_avatar_chip_draw" )
require_ex( "luacommon/time_event/time_event_log_handle_reset" )
-- CAMP to c++
g_campmng:c_read_cfg( CAMPS )
CAMPS = nil

g_curvemng:c_reload( BEZIER_CURVES )
BEZIER_CURVES = nil

--if g_debug then
    require_ex( "testcase/testcase" )
--end

if g_debug then 
    require_ex( "luacommon/testcase/test_common/test_guild_weekend" )
    require_ex( "luacommon/testcase/test_common/test_activity" )
end
require_ex( "luacommon/testcase/test_common/test_truncheon" )

function init()
    testcase.test()
    login_mng.init()
    time_event.init()
    event_calendar.init()
    mystic_dealer.init_mystic_tick_func()
    client_access_switch.init_access_switch()
    drop_addition_t.check_holiday()
    event_guild_campfire_party.init()
    event_god_divination.init()
    attend_push_mng.init_attend_push_mng()
    event_one_gold_lucky_draw.init()
    time_event_log_handle_reset.init()
end

require_ex( "global" )
require_ex( "net/dbclient" )
require_ex( "net/bfclient" )
require_ex( "net/gamesvr" )
require_ex( "net/loginclient" )
require_ex( "luacommon/net/logclient_tw" )
require_ex( "luacommon/net/logclient" )
require_ex( "luacommon/net/gmclient" )
require_ex( "luacommon/net/http_mng" )
require_ex( "luacommon/splus_sdk/splus_verify" )
require_ex( "luacommon/splus_sdk/order_mng" )
require_ex( "luacommon/net/gmsvr" )

require_ex( "event/event_wild/wild_mng_guild" )
require_ex( "event/event_wild/wild_mng" )
require_ex( "luacommon/event/colossus_mng" )
require_ex( "event/event_wild/colossus_mng_gs" )
require_ex( "luacommon/announce_mng" )

require_ex( "luacommon/hall/hall_mng" )
require_ex( "luacommon/hall/hall_mng_gs" )
require_ex( "luacommon/hall/hall_mng_upvote_gs" )

require_ex( "luacommon/event/egg_mng" )
require_ex( "luacommon/event/egg_feed_event" )


-- init
init()

require_ex( "luacommon/friend/friend_testcase" )

require_ex( "luacommon/map/map_mng" )

require_ex( "luacommon/rebate_mng" )
