
function require_ex( _mname )
    package.loaded[_mname] = nil
    return require( _mname )    
end

------------------------------------------------------------------------------------------
--                              初始化LuaJIT
------------------------------------------------------------------------------------------
if g_debug then
    package.path = "./?.lua;./?.lc"
else
    --package.path = "./?.lc"
    package.path = "./?.lc"
end

require_ex( "jit/opt" ) 

if g_debug then
    if jit then
        jit.debug(2)
        jit.opt.start(3)
        c_log( "++++++++++++++++++LUAJIT(v1) DEBUG OPT LEVEL 3+++++++++++++++++++" )
    end
else
    if jit then
        jit.debug(0)
        jit.opt.start(3)
        c_log( "++++++++++++++++++LUAJIT(v1) RELEASE OPT LEVEL 3+++++++++++++++++++" )
    end
end

math.randomseed( os.time() )

------------------------------------------------------------------------------------------
--                              加载所有模块
------------------------------------------------------------------------------------------
WING_SKILLS = require_ex("luacommon/setting/WING_SKILLS")
EGG_GLOBAL_CONFIG = require_ex("luacommon/setting/EGG_GLOBAL_CONFIG")
INSTANCE_CFG = require_ex("luacommon/setting/INSTANCE_CFG") 
ACTIVITY_INSTANCE_CONFIG = require_ex("luacommon/setting/ACTIVITY_INSTANCE_CONFIG")
SKILLS = require_ex( "luacommon/setting/SKILLS" )
BUFFS = require_ex( "luacommon/setting/BUFFS" )
RECHARGE_ITEM_LIST = require_ex( "luacommon/setting/RECHARGE_ITEM_LIST" )
RECHARGE_VIP_CONFIG = require_ex( "luacommon/setting/RECHARGE_VIP_CONFIG" )
TIME_EVENT = require_ex( "luacommon/setting/TIME_EVENT" )
TIME_CTRL = require_ex( "luacommon/setting/TIME_CTRL" )
QUEST_2_MAMMONS_TREASURE = require_ex( "luacommon/setting/QUEST_2_MAMMONS_TREASURE")
HIGHEST_SURVIVAL_CONFIG = require_ex("luacommon/setting/HIGHEST_SURVIVAL_CONFIG")
GOBLIN_MARKET_CONFIG = require_ex( "luacommon/setting/GOBLIN_MARKET_CONFIG" )
PRAY_SYS_CONFIG = require_ex( "luacommon/setting/PRAY_SYS_CONFIG" )
NEWBIE_GUIDE_CONFIG = require_ex( "luacommon/setting/NEWBIE_GUIDE_CONFIG" )
ENERGY_CONFIG = require_ex( "luacommon/setting/ENERGY_CONFIG" )
BULLETIN = require_ex( "luacommon/setting/BULLETIN")
EQUIPS = require_ex( "luacommon/setting/EQUIPS" )
PLAYER_ATTR = require_ex("luacommon/setting/PLAYER_ATTR")
MYSTIC_SYS_CONFIG = require_ex( "luacommon/setting/MYSTIC_SYS_CONFIG" )
DAILY_GOALS = require_ex( "luacommon/setting/DAILY_GOALS" )
TRIGGER_DATA = require_ex( "luacommon/setting/TRIGGER_DATA" )
ITEMS = require_ex("luacommon/setting/ITEMS")
GUILD_LEVEL_CONFIG = require_ex( "luacommon/setting/GUILD_LEVEL_CONFIG" )
GUILD_POPULARITY_CONFIG = require_ex( "luacommon/setting/GUILD_POPULARITY_CONFIG" )
GUILD_ROLE_PRIVILEGE_CONFIG = require_ex( "luacommon/setting/GUILD_ROLE_PRIVILEGE_CONFIG" )
GUILD_SYSTEM_CONFIG = require_ex( "luacommon/setting/GUILD_SYSTEM_CONFIG" )
EQUIP_EXCHANGE_SHOP_CONFIG = require_ex( "luacommon/setting/EQUIP_EXCHANGE_SHOP_CONFIG" )
PERMANENT_ATTR_ITEM_CONFIG = require_ex( "luacommon/setting/PERMANENT_ATTR_ITEM_CONFIG" ) 
GUILD_PVP_CONFIG = require_ex( "luacommon/setting/GUILD_PVP_CONFIG" )
GUILD_VICE_PROFESSION_CONFIG = require_ex( "luacommon/setting/GUILD_VICE_PROFESSION_CONFIG" )
HOLIDAY_SIGNIN_AWARD_GLOBAL_CONFIG = require_ex( "luacommon/setting/HOLIDAY_SIGNIN_AWARD_GLOBAL_CONFIG" )
HOLIDAY_SIGNIN_AWARD_CONFIG = require_ex( "luacommon/setting/HOLIDAY_SIGNIN_AWARD_CONFIG" )
MONSTER_DATA = require_ex("luacommon/setting/MONSTER_DATA") 

TRUNCHEON_REFINE = require_ex( "luacommon/setting/TRUNCHEON_REFINE" )
TRUNCHEON_REBORN = require_ex( "luacommon/setting/TRUNCHEON_REBORN" )
TRUNCHEON_REBORN_COST = require_ex( "luacommon/setting/TRUNCHEON_REBORN_COST" )
TRUNCHEON_LETTERING = require_ex( "luacommon/setting/TRUNCHEON_LETTERING" )
TRUNCHEON_LETTERING_GROUP = require_ex( "luacommon/setting/TRUNCHEON_LETTERING_GROUP" )
TRUNCHEON_LETTERING_DICT = require_ex( "luacommon/setting/TRUNCHEON_LETTERING_DICT" )
GUILD_MERCHANT_RUNNER_CONFIG = require_ex( "luacommon/setting/GUILD_MERCHANT_RUNNER_CONFIG" )
GUILD_MERCHANT_RUNNER_NPC_CONFIG = require_ex( "luacommon/setting/GUILD_MERCHANT_RUNNER_NPC_CONFIG" )
GUILD_MERCHANT_RUNNER_ITEM_CONFIG = require_ex( "luacommon/setting/GUILD_MERCHANT_RUNNER_ITEM_CONFIG" )
GUILD_MERCHANT_RUNNER_NPC_BUY_CONFIG = require_ex( "luacommon/setting/GUILD_MERCHANT_RUNNER_NPC_BUY_CONFIG" )
GUILD_MERCHANT_RUNNER_NPC_SELL_CONFIG = require_ex( "luacommon/setting/GUILD_MERCHANT_RUNNER_NPC_SELL_CONFIG" )
GUILDPROF_TASK = require_ex( "luacommon/setting/GUILDPROF_TASK" )
GUILDPROF_TASK_PRIZE_CONFIG = require_ex( "luacommon/setting/GUILDPROF_TASK_PRIZE_CONFIG" )
GUILDPROF_TARGETS = require_ex( "luacommon/setting/GUILDPROF_TARGETS" )
GUILD_INST_CFG = require_ex( "luacommon/setting/GUILD_INST_CFG" )
GUILDPROF_TASK_SYS_CFG = require_ex( "luacommon/setting/GUILDPROF_TASK_SYS_CFG" )
ELAM_MILITARY_SUPPLIES_CFG = require_ex( "luacommon/setting/ELAM_MILITARY_SUPPLIES_CFG" )
GOD_DIVINATION_CONFIG = require_ex( "luacommon/setting/GOD_DIVINATION_CONFIG" )
GOD_DIVINATION_ASTROLABE_CONFIG = require_ex( "luacommon/setting/GOD_DIVINATION_ASTROLABE_CONFIG" )
GOD_DIVINATION_RUNE_CONFIG = require_ex( "luacommon/setting/GOD_DIVINATION_RUNE_CONFIG" )
RECHARGE_AWARD_CONFIG = require_ex(  "luacommon/setting/RECHARGE_AWARD_CONFIG" )
DAILY_ONLINE_AWARD_CONFIG = require_ex( "luacommon/setting/DAILY_ONLINE_AWARD_CONFIG" )
CYCLED_RECHARGE_AWARD_CONFIG = require_ex( "luacommon/setting/CYCLED_RECHARGE_AWARD_CONFIG" )
GROWTH_FUND_CONFIG = require_ex( "luacommon/setting/GROWTH_FUND_CONFIG" )
GROWTH_FUND_GLOBAL_CONFIG = require_ex( "luacommon/setting/GROWTH_FUND_GLOBAL_CONFIG" )
LOGIN_ACTIVITY_CONFIG = require_ex( "luacommon/setting/LOGIN_ACTIVITY_CONFIG" )
HALF_PRICE_CONFIG = require_ex( "luacommon/setting/HALF_PRICE_CONFIG" )
FIRST_RECHARGE_AWARD = require_ex( "luacommon/setting/FIRST_RECHARGE_AWARD" )
GUILD_ROLE_WELFARE_GLOBAL_CONFIG = require_ex( "luacommon/setting/GUILD_ROLE_WELFARE_GLOBAL_CONFIG" )
GUILD_ROLE_RANK_AWARD_CONFIG = require_ex( "luacommon/setting/GUILD_ROLE_RANK_AWARD_CONFIG" )
GUILD_ROLE_PROTECT_CITY_AWARD_CONFIG = require_ex( "luacommon/setting/GUILD_ROLE_PROTECT_CITY_AWARD_CONFIG" )
GUILD_ROLE_FIGHT_AWARD_CONFIG = require_ex( "luacommon/setting/GUILD_ROLE_FIGHT_AWARD_CONFIG" )
GUILD_ROLE_ITEM_LIB_CONFIG = require_ex( "luacommon/setting/GUILD_ROLE_ITEM_LIB_CONFIG" )
CHAT_CONFIG = require_ex( "luacommon/setting/CHAT_CONFIG" )
RECHARGE_BIG_AWARD_CONFIG = require_ex( "luacommon/setting/RECHARGE_BIG_AWARD_CONFIG" )
LEVEL_RECHARGE_ITEM_GIFT_GLOBAL_CONFIG = require_ex( "luacommon/setting/LEVEL_RECHARGE_ITEM_GIFT_GLOBAL_CONFIG" )
LEVEL_RECHARGE_ITEM_GIFT = require_ex( "luacommon/setting/LEVEL_RECHARGE_ITEM_GIFT" )
ONE_GOLD_LUCKY_DRAW_GOODS_CONFIG = require_ex( "luacommon/setting/ONE_GOLD_LUCKY_DRAW_GOODS_CONFIG" )
ONE_GOLD_LUCKY_DRAW_GLOBAL_CONFIG = require_ex( "luacommon/setting/ONE_GOLD_LUCKY_DRAW_GLOBAL_CONFIG" )
ONE_GOLD_LUCKY_DRAW_BONUS_GOODS_CONFIG = require_ex( "luacommon/setting/ONE_GOLD_LUCKY_DRAW_BONUS_GOODS_CONFIG" )
CHAPTER_CONFIG = require_ex( "luacommon/setting/CHAPTER_CONFIG" )
CHAT_GIFT_GLOBAL_CONFIG = require_ex( "luacommon/setting/CHAT_GIFT_GLOBAL_CONFIG" )
CHRISTMAS_SELL_GLOBAL_CONFIG = require_ex( "luacommon/setting/CHRISTMAS_SELL_GLOBAL_CONFIG" )
CHRISTMAS_RECHARGE_LUCKY_DRAW_GLOBAL_CONFIG = require_ex( "luacommon/setting/CHRISTMAS_RECHARGE_LUCKY_DRAW_GLOBAL_CONFIG" )
CHRISTMAS_SELL_ITEM_CONFIG = require_ex( "luacommon/setting/CHRISTMAS_SELL_ITEM_CONFIG" )
WING_UPGRADE_CONFIG = require_ex( "luacommon/setting/WING_UPGRADE_CONFIG" )
WING_CONFIG = require_ex( "luacommon/setting/WING_CONFIG" )
--$SETTING_FILES

require_ex("luacommon/setting/JOBS") 

require_ex( "luacommon/share/share_const" )
require_ex( "luacommon/login_code" )
require_ex( "luacommon/limit" )
require_ex( "luacommon/msg" )
require_ex( "luacommon/utils" )
require_ex( "luacommon/formula/player_attr" )
require_ex( "luacommon/formula/fight_action" )

require_ex( "luacommon/time_event/time_event" )
require_ex( "luacommon/time_ctrl/time_ctrl" )

require_ex( "luacommon/item/bag_t" )
require_ex( "luacommon/item/item_t_inherit")
require_ex( "luacommon/item/item_t_equip_gs")
require_ex( "luacommon/item/item_t_equip" )
require_ex( "luacommon/item/item_t_use" )
require_ex( "luacommon/item/item_t_const" )
require_ex( "luacommon/item/item_t" )
require_ex( "luacommon/object/obj_t" )
require_ex( "luacommon/object/ctrl_t" )
require_ex( "luacommon/object/spirit_t_module" )
require_ex( "luacommon/object/spirit_t_buff" )
require_ex( "luacommon/object/spirit_t_pasv" )
require_ex( "luacommon/object/spirit_t_fight" )
require_ex( "luacommon/object/spirit_t" )
require_ex( "luacommon/object/player_t_module" )
require_ex( "luacommon/object/player_t_net" )
require_ex( "luacommon/object/player_t_fight" )
require_ex( "luacommon/object/player_t_copy" )
require_ex( "luacommon/object/player_t_skill" )
require_ex( "luacommon/object/player_t_item" )
require_ex( "luacommon/object/player_t_rune" )
require_ex( "luacommon/object/player_t_avatar" )
require_ex( "luacommon/object/player_t_pet" )
require_ex( "luacommon/object/player_t_sanding" )
require_ex( "luacommon/object/player_t_quest")
require_ex( "luacommon/object/player_t_time" )
require_ex( "luacommon/object/player_t_param" )
require_ex( "luacommon/object/player_t_recharge" )
require_ex( "luacommon/object/player_t_goblin_market")
require_ex( "luacommon/object/player_t_pray")
require_ex( "luacommon/object/player_t_newbie_guide")
require_ex( "luacommon/object/player_t_mystic" )
require_ex( "luacommon/object/player_t_shop" )
require_ex( "luacommon/object/player_t_gold_exchange" )
require_ex( "luacommon/object/player_t_tower" )
require_ex( "luacommon/object/player_t_palace" )
require_ex( "luacommon/object/player_t_team_ladder" )
require_ex( "luacommon/object/player_t_celebration" )
require_ex( "luacommon/object/player_t_parchment" )
require_ex( "luacommon/object/player_t_daily_goals")
require_ex( "luacommon/object/player_t_attend" )
require_ex( "luacommon/object/player_t_rmb" )
require_ex( "luacommon/object/player_t_runner" )
require_ex( "luacommon/object/player_t_holiday_event" )
require_ex( "luacommon/object/player_t_ladder" )
require_ex( "luacommon/object/player_t_like" )
require_ex( "luacommon/object/player_t_chapter" )
require_ex( "luacommon/object/player_t_title" )
require_ex( "luacommon/object/player_t_guild" )
require_ex( "luacommon/object/player_t_auction" )
require_ex( "luacommon/object/player_t_customer_service" )
require_ex( "luacommon/object/player_t_god_divination" )
require_ex("luacommon/object/player_t_friend")
require_ex( "luacommon/object/player_t_weekly_task" )
require_ex( "luacommon/object/player_t_equip_exchange_shop" )
require_ex( "luacommon/object/player_t_permanent_attr" )
require_ex( "luacommon/object/player_t_inst" )
require_ex( "luacommon/object/player_t_truncheon" )
require_ex( "luacommon/object/player_t_guild_profession" )
require_ex( "luacommon/object/player_t_wild" )
require_ex( "luacommon/object/player_t_welfare" )
require_ex( "luacommon/object/player_t_guild_merchant_task" )
require_ex( "luacommon/object/player_t_guildprof_task" )
require_ex( "luacommon/object/player_t_guild_donation" )
require_ex( "luacommon/object/player_t_trade" )
-- require_ex( "luacommon/object/player_t_soul_contract" )
require_ex( "luacommon/object/player_t_soul" )
require_ex( "luacommon/object/player_t_mastery" )
require_ex( "luacommon/object/player_t_carnival" )
require_ex( "luacommon/object/player_t_element" )
require_ex( "luacommon/object/player_t_vip" )
require_ex( "luacommon/object/player_t_prevent_kill_cheat" )
require_ex( "luacommon/object/player_t_guild_pve" )
require_ex( "luacommon/object/player_t_holiday_signin_award" )
require_ex( "luacommon/object/player_t_monthly_signin_award" )
require_ex( "luacommon/object/player_t_mall" )
require_ex( "luacommon/object/player_t_daily_online_award" )
require_ex( "luacommon/object/player_t_cycled_recharge_award" )
require_ex( "luacommon/object/player_t_growth_fund" )
require_ex( "luacommon/object/player_t_login_activity" )
require_ex( "luacommon/object/player_t_sanding" )
require_ex( "luacommon/object/player_t_chat" )
require_ex( "luacommon/object/player_t_share" )
require_ex( "luacommon/object/player_t_survey" )
require_ex( "luacommon/object/player_t_small_data" )
require_ex( "luacommon/object/player_t_battle_justice" )
require_ex( "luacommon/object/player_t_hall" )
require_ex( "luacommon/object/player_t_level_recharge" )
require_ex( "luacommon/object/player_t_one_gold_lucky_draw" )
require_ex( "luacommon/object/player_t_egg" )
require_ex( "luacommon/object/player_t_festival" )
require_ex( "luacommon/object/player_t_player_chat_gift" )
require_ex( "luacommon/object/player_t_christmas_sell" )
require_ex( "luacommon/object/player_t_christmas_recharge_lucky_draw" )
require_ex( "luacommon/object/player_t_wing_system" )
--$PLAYER_MODULE
require_ex( "luacommon/object/player_t" )
require_ex( "luacommon/object/monster_t_module" )
require_ex( "luacommon/object/monster_t_robot" )
require_ex( "luacommon/object/monster_t" )
require_ex( "luacommon/object/bullet_t" )
require_ex( "luacommon/object/missile_t" )
require_ex( "luacommon/object/shop_t" )
require_ex( "luacommon/object/gold_exchange_t" )
require_ex( "luacommon/mail/mail_t" )
require_ex( "luacommon/mail/mail_box_t" )
require_ex( "luacommon/item/bag_t_warehouse" )

require_ex( "luacommon/object/summon_mng" )
require_ex( "luacommon/object/magic_area_mng" )
require_ex( "luacommon/object/magic_area_t" )

require_ex( "luacommon/trigger_impl/trigger_extend/trigger_const_params" )
require_ex( "luacommon/module/trigger_timer" )
require_ex( "luacommon/trigger_impl/trigger_action_t" )
require_ex( "luacommon/trigger_impl/trigger_impl_t" )
require_ex( "luacommon/trigger_impl/aoi_action_impl_t" )
require_ex( "luacommon/trigger_impl/aoi_impl_t" )
require_ex( "luacommon/trigger_impl/battle_station")
require_ex( "luacommon/trigger_impl/counter_impl_t" )
require_ex( "luacommon/trigger_impl/kill_counter_impl_t" )
require_ex( "luacommon/trigger_impl/sfx_player_impl_t" )
require_ex( "luacommon/trigger_impl/skill_user_impl_t" )
require_ex( "luacommon/trigger_impl/cinema_impl_t" )
require_ex( "luacommon/trigger_impl/summon_impl_t" )
require_ex( "luacommon/trigger_impl/func_impl_t" )
require_ex( "luacommon/trigger_impl/rater_impl_t" )
require_ex( "luacommon/trigger_impl/ctrl_npc_impl_t" )
require_ex( "luacommon/trigger_impl/onhit_impl_t" )
require_ex( "luacommon/trigger_impl/slot_machine_impl_t" )
require_ex( "luacommon/trigger_impl/task_impl_t")
require_ex( "luacommon/trigger_impl/wandering_singer_impl_t" )
require_ex( "luacommon/trigger_impl/progress_impl_t" )
require_ex( "luacommon/trigger_impl/aoi_toggle_impl_t" )
require_ex( "luacommon/trigger_impl/trigger_extend/trigger_jixiemicheng_random" )
require_ex( "luacommon/trigger_impl/trigger_func" )
require_ex( "luacommon/trigger_impl/pass_counter_impl_t")
require_ex( "luacommon/trigger_impl/inscription_impl_t")
require_ex( "luacommon/trigger_impl/trap_impl_t" )
require_ex( "luacommon/trigger_impl/stay_statics_impl_t" )
require_ex( "luacommon/object/trigger_t" )

require_ex( "luacommon/plane/planemng" )
require_ex( "luacommon/plane/plane_t" )
require_ex( "luacommon/instance/instance_t_const")
require_ex( "luacommon/instance/instance_t")

require_ex( "luacommon/quest/target_type")
require_ex( "luacommon/quest/quest_target_t")
require_ex( "luacommon/quest/quest_main_t")
require_ex( "luacommon/quest/quest_worldmap_t" )
require_ex( "luacommon/quest/quest_mammons_treasure" )
require_ex( "luacommon/quest/quest_highest_survival_t" )

require_ex( "luacommon/event/event_price_board/event_price_board" )

-- 好友
require_ex( "luacommon/friend/friend_const" )
require_ex( "luacommon/friend/friend_mng" )
require_ex( "luacommon/friend/friend_mng_core" )
require_ex( "luacommon/friend/friend_mng_center" )
require_ex( "luacommon/friend/friend_mng_db" )
require_ex( "luacommon/friend/friend_t" )
require_ex( "luacommon/friend/friend_set_t" )
require_ex( "luacommon/friend/friend_history_t" )
require_ex( "luacommon/friend/friend_history_list_t" )

--公会
require_ex( "luacommon/guild/guild_mng" )
require_ex( "luacommon/guild/guild_mng_workflow_db" )
require_ex( "luacommon/guild/guild_mng_workflow_add_popu" )
require_ex( "luacommon/guild/guild_mng_workflow_apply" )
require_ex( "luacommon/guild/guild_mng_workflow_change_desc" )
require_ex( "luacommon/guild/guild_mng_workflow_create" )
require_ex( "luacommon/guild/guild_mng_workflow_invite" )
require_ex( "luacommon/guild/guild_mng_workflow_kick" )
require_ex( "luacommon/guild/guild_mng_workflow_login" )
require_ex( "luacommon/guild/guild_mng_workflow_quit" )
require_ex( "luacommon/guild/guild_mng_workflow_refresh" )
require_ex( "luacommon/guild/guild_mng_workflow_search" )
require_ex( "luacommon/guild/guild_mng_workflow_set_role" )
require_ex( "luacommon/guild/guild_mng_profession" )
require_ex( "luacommon/guild/guild_mng_donation" )
require_ex( "luacommon/guild/guild_mng_utils" )
require_ex( "luacommon/guild/guild_mng_hash_array" )
require_ex( "luacommon/guild/guild_cache" )
require_ex( "luacommon/module/player_gs_offline_op_mng" )

require_ex( "luacommon/object/player_t_team" )
require_ex( "luacommon/team/team_t") 

require_ex( "luacommon/recruit/recruit_t") 
require_ex( "luacommon/recruit/recruit_member_t") 


require_ex( "object/ctrl_mng" )
require_ex( "logic/robot_gm" )
require_ex( "logic/robot_nothing" )
require_ex( "logic/robot_move" )
require_ex( "logic/robot_skill" )
require_ex( "logic/robot_shop" )
require_ex( "logic/robot_trade" )
require_ex( "logic/robot_instance" )
require_ex( "logic/robot_chat" )
require_ex( "logic/robot_recharge" )
require_ex( "logic/robot_team" )
require_ex( "logic/robot_bf" )
require_ex( "logic/robot_tamriel_match" )
require_ex( "net/robotclient" )
require_ex( "timer/timers" )
require_ex( "luacommon/timer/timers" )
require_ex( "luacommon/chat/chat_msg_t" )
require_ex( "luacommon/chat/chat_mng" )
require_ex( "luacommon/chat/chat_net" )
require_ex( "luacommon/announce_mng" )

require_ex( "luacommon/net/http_mng" )

if g_debug then
    require_ex( "testcase/testcase" )
end
