#ifndef __SHARE_CONST_H__
#define __SHARE_CONST_H__

#define SHARE_ACT_NONE 0
#define SHARE_ACT_LOOP 1
#define SHARE_ACT_STAND 2
#define SHARE_ACT_ONCE_STAND 3
#define SHARE_ACT_ONCE_STILL 4
#define SHARE_ACT_SPAWN 5

#define PATROL_ANI_NONE -1
#define PATROL_ANI_WALK 0
#define PATROL_ANI_RUN 1
#define PATROL_ANI_RUSH 2

#define SHARE_ANI_NONE 100
#define SHARE_ANI_WALK 101
#define SHARE_ANI_WALK_LEFT 102
#define SHARE_ANI_WALK_RIGHT 103
#define SHARE_ANI_WALK_BACK 104
#define SHARE_ANI_WALK_02 105
#define SHARE_ANI_WALK_03 106
#define SHARE_ANI_WALK_04 107

#define SHARE_ANI_RUN 120
#define SHARE_ANI_RUN_LEFT 121
#define SHARE_ANI_RUN_RIGHT 122
#define SHARE_ANI_RUN_BACK 123
#define SHARE_ANI_RUN_02 124
#define SHARE_ANI_RUN_03 125
#define SHARE_ANI_RUN_MASTER 126
#define SHARE_ANI_RUN_BATTLE 127

#define SHARE_ANI_RUSH 140
#define SHARE_ANI_RUSH_FRONT 141
#define SHARE_ANI_RUSH_RIGHT 142
#define SHARE_ANI_RUSH_02 143
#define SHARE_ANI_RUSH_03 144
#define SHARE_ANI_RUSH_MASTER 145

#define SHARE_AI_MSG_NONE 0
#define SHARE_AI_SKILL_END 1
#define SHARE_AI_START_CONDITION 4
#define SHARE_AI_STOP_CONDITION 5
#define SHARE_AI_ON_DAMAGE 8
#define SHARE_AI_FORCE_LEAVE_COMBAT 9
#define SHARE_AI_REQUEST_STOP 10
#define SHARE_AI_ON_DIE 11

#define SHARE_AI_SPAWN_NONE 0
#define SHARE_AI_SPAWN_JUMP 1
#define SHARE_AI_SPAWN_PATROL 2
#define SHARE_AI_SPAWN_ACT 3

#define SHARE_AI_NORMAL_MODE 0
#define SHARE_AI_DRAMA_EXEC_MODE 1
#define SHARE_AI_DRAMA_SEEK_MODE 2
#define SHARE_AI_DRAMA_COMBAT_MODE 3

#define SHARE_TURN_NONE 0
#define SHARE_TURN_STILL 1
#define SHARE_TURN_TO_CHAR_ONCE 2
#define SHARE_TURN_TO_CHAR_ALWAYS 3
#define SHARE_TURN_TO_PATH 4
#define SHARE_TURN_TO_DIR 5
#define SHARE_TURN_TO_CHAR_ONCE_PATH 6
#define SHARE_TURN_TO_DIR_PATH 7
#define SHARE_TURN_DIRECTLY 8

#define SHARE_DAMAGE_RANGE_REMOTE 2

#define AI_ON_HIT 1
#define AI_ON_RESUME 3
#define AI_ON_DAMAGE 4
#define AI_SKILL_END 5

#define DEFAULT_OFF_ANGLE 361 
#define SCENE_CELL 1
#define MAX_SFX_OPEN_FLAG 3
#define TRIGGER_STATE_INVALID -1

#endif  // __SHARE_CONST_H__
